<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<Import Project="..\Directory.Build.targets"/>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)\BannedSymbols.txt" />
	</ItemGroup>
</Project>
