// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1
{
    ///<summary>
    ///The primary selection device manager is a singleton global object that
    ///provides access to the primary selection. It allows to create
    ///wp_primary_selection_source objects, as well as retrieving the per-seat
    ///wp_primary_selection_device objects.
    ///</summary>
 
    public sealed unsafe partial class ZwpPrimarySelectionDeviceManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_primary_selection_device_manager_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("create_source") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_device") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpPrimarySelectionDeviceManagerV1), (ctx) => new ZwpPrimarySelectionDeviceManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Create a new primary selection source.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 CreateSource(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.ArgNewId();
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///Create a new data device for a given seat.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 GetDevice(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat @seat, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@seat);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///Destroy the primary selection device manager.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private ZwpPrimarySelectionDeviceManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpPrimarySelectionDeviceManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpPrimarySelectionDeviceManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    public sealed unsafe partial class ZwpPrimarySelectionDeviceV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_primary_selection_device_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_selection") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1.ProxyType).AsNullable()) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("data_offer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.ProxyType)) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("selection") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.ProxyType).AsNullable()) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpPrimarySelectionDeviceV1), (ctx) => new ZwpPrimarySelectionDeviceV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Replaces the current selection. The previous owner of the primary
        ///selection will receive a wp_primary_selection_source.cancelled event.
        ///
        ///To unset the selection, set the source to NULL.
        ///</summary>
 
        public void SetSelection(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1? @source, uint @serial)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Arg(@source);
                __call.Arg(@serial);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Destroy the primary selection device.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Introduces a new wp_primary_selection_offer object that may be used
            ///to receive the current primary selection. Immediately following this
            ///event, the new wp_primary_selection_offer object will send
            ///wp_primary_selection_offer.offer events to describe the offered mime
            ///types.
            ///</summary>
 
            protected virtual void DataOffer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.NewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.Listener> @offer)
            {
            }

            ///<summary>
            ///The wp_primary_selection_device.selection event is sent to notify the
            ///client of a new primary selection. This event is sent after the
            ///wp_primary_selection.data_offer event introducing this object, and after
            ///the offer has announced its mimetypes through
            ///wp_primary_selection_offer.offer.
            ///
            ///The data_offer is valid until a new offer or NULL is received
            ///or until the client loses keyboard focus. The client must destroy the
            ///previous selection data_offer, if any, upon receiving this event.
            ///</summary>
 
            protected virtual void Selection(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1? @id)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.DataOffer(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1)arguments.Sender, 
                        arguments.GetNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.Listener>(0));
                        break;
                    case 1:
                        this.Selection(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1)arguments.Sender, 
                        arguments.GetProxy<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1>(0));
                        break;
                }
            }

            ///<summary>
            ///The wp_primary_selection_device.selection event is sent to notify the
            ///client of a new primary selection. This event is sent after the
            ///wp_primary_selection.data_offer event introducing this object, and after
            ///the offer has announced its mimetypes through
            ///wp_primary_selection_offer.offer.
            ///
            ///The data_offer is valid until a new offer or NULL is received
            ///or until the client loses keyboard focus. The client must destroy the
            ///previous selection data_offer, if any, upon receiving this event.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void DataOfferDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.NewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.Listener> @offer);
                public DataOfferDelegate? OnDataOffer { get; init; }

                protected override void DataOffer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.NewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.Listener> @offer) => OnDataOffer?.Invoke(eventSender, @offer);
                public delegate void SelectionDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1? @id);
                public SelectionDelegate? OnSelection { get; init; }

                protected override void Selection(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionDeviceV1 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1? @id) => OnSelection?.Invoke(eventSender, @id);
            }
        }

        private ZwpPrimarySelectionDeviceV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpPrimarySelectionDeviceV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpPrimarySelectionDeviceV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///A wp_primary_selection_offer represents an offer to transfer the contents
    ///of the primary selection clipboard to the client. Similar to
    ///wl_data_offer, the offer also describes the mime types that the data can
    ///be converted to and provides the mechanisms for transferring the data
    ///directly to the client.
    ///</summary>
 
    public sealed unsafe partial class ZwpPrimarySelectionOfferV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_primary_selection_offer_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("receive") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.FileDescriptor) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("offer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpPrimarySelectionOfferV1), (ctx) => new ZwpPrimarySelectionOfferV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///To transfer the contents of the primary selection clipboard, the client
        ///issues this request and indicates the mime type that it wants to
        ///receive. The transfer happens through the passed file descriptor
        ///(typically created with the pipe system call). The source client writes
        ///the data in the mime type representation requested and then closes the
        ///file descriptor.
        ///
        ///The receiving client reads from the read end of the pipe until EOF and
        ///closes its end, at which point the transfer is complete.
        ///</summary>
 
        public void Receive(string @mimeType, int @fd)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Arg(@mimeType);
                __call.Arg(@fd);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Destroy the primary selection offer.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Sent immediately after creating announcing the
            ///wp_primary_selection_offer through
            ///wp_primary_selection_device.data_offer. One event is sent per offered
            ///mime type.
            ///</summary>
 
            protected virtual void Offer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1 eventSender, string @mimeType)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Offer(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1)arguments.Sender, 
                        arguments.GetString(0)!);
                        break;
                }
            }

            ///<summary>
            ///Sent immediately after creating announcing the
            ///wp_primary_selection_offer through
            ///wp_primary_selection_device.data_offer. One event is sent per offered
            ///mime type.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void OfferDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1 eventSender, string @mimeType);
                public OfferDelegate? OnOffer { get; init; }

                protected override void Offer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionOfferV1 eventSender, string @mimeType) => OnOffer?.Invoke(eventSender, @mimeType);
            }
        }

        private ZwpPrimarySelectionOfferV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpPrimarySelectionOfferV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpPrimarySelectionOfferV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///The source side of a wp_primary_selection_offer, it provides a way to
    ///describe the offered data and respond to requests to transfer the
    ///requested contents of the primary selection clipboard.
    ///</summary>
 
    public sealed unsafe partial class ZwpPrimarySelectionSourceV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_primary_selection_source_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("offer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("send") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.FileDescriptor) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("cancelled") 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpPrimarySelectionSourceV1), (ctx) => new ZwpPrimarySelectionSourceV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///This request adds a mime type to the set of mime types advertised to
        ///targets. Can be called several times to offer multiple types.
        ///</summary>
 
        public void Offer(string @mimeType)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Arg(@mimeType);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Destroy the primary selection source.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Request for the current primary selection contents from the client.
            ///Send the specified mime type over the passed file descriptor, then
            ///close it.
            ///</summary>
 
            protected virtual void Send(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender, string @mimeType, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandFd @fd)
            {
            }

            ///<summary>
            ///This primary selection source is no longer valid. The client should
            ///clean up and destroy this primary selection source.
            ///</summary>
 
            protected virtual void Cancelled(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Send(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1)arguments.Sender, 
                        arguments.GetString(0)!, 
                        arguments.GetFd(1));
                        break;
                    case 1:
                        this.Cancelled(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1)arguments.Sender);
                        break;
                }
            }

            ///<summary>
            ///This primary selection source is no longer valid. The client should
            ///clean up and destroy this primary selection source.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void SendDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender, string @mimeType, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandFd @fd);
                public SendDelegate? OnSend { get; init; }

                protected override void Send(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender, string @mimeType, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandFd @fd) => OnSend?.Invoke(eventSender, @mimeType, @fd);
                public delegate void CancelledDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender);
                public CancelledDelegate? OnCancelled { get; init; }

                protected override void Cancelled(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.WpPrimarySelectionUnstableV1.ZwpPrimarySelectionSourceV1 eventSender) => OnCancelled?.Invoke(eventSender);
            }
        }

        private ZwpPrimarySelectionSourceV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpPrimarySelectionSourceV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpPrimarySelectionSourceV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}