// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1
{
    ///<summary>
    ///This interface allows clients to create toplevel window icons and set
    ///them on toplevel windows to be displayed to the user.
    ///</summary>
 
    public sealed unsafe partial class XdgToplevelIconManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("xdg_toplevel_icon_manager_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("create_icon") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_icon") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgShell.XdgToplevel.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1.ProxyType).AsNullable()) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("icon_size") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("done") 
        .Build() 
        ) 
        .Build() 
        , typeof(XdgToplevelIconManagerV1), (ctx) => new XdgToplevelIconManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the toplevel icon manager.
        ///This does not destroy objects created with the manager.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Creates a new icon object. This icon can then be attached to a
        ///xdg_toplevel via the 'set_icon' request.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1 CreateIcon(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///This request assigns the icon 'icon' to 'toplevel', or clears the
        ///toplevel icon if 'icon' was null.
        ///This state is double-buffered and is applied on the next
        ///wl_surface.commit of the toplevel.
        ///
        ///After making this call, the xdg_toplevel_icon_v1 provided as 'icon'
        ///can be destroyed by the client without 'toplevel' losing its icon.
        ///The xdg_toplevel_icon_v1 is immutable from this point, and any
        ///future attempts to change it must raise the
        ///'xdg_toplevel_icon_v1.immutable' protocol error.
        ///
        ///The compositor must set the toplevel icon from either the pixel data
        ///the icon provides, or by loading a stock icon using the icon name.
        ///See the description of 'xdg_toplevel_icon_v1' for details.
        ///
        ///If 'icon' is set to null, the icon of the respective toplevel is reset
        ///to its default icon (usually the icon of the application, derived from
        ///its desktop-entry file, or a placeholder icon).
        ///If this request is passed an icon with no pixel buffers or icon name
        ///assigned, the icon must be reset just like if 'icon' was null.
        ///</summary>
 
        public void SetIcon(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgShell.XdgToplevel @toplevel, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1? @icon)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@toplevel);
                __call.Arg(@icon);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///This event indicates an icon size the compositor prefers to be
            ///available if the client has scalable icons and can render to any size.
            ///
            ///When the 'xdg_toplevel_icon_manager_v1' object is created, the
            ///compositor may send one or more 'icon_size' events to describe the list
            ///of preferred icon sizes. If the compositor has no size preference, it
            ///may not send any 'icon_size' event, and it is up to the client to
            ///decide a suitable icon size.
            ///
            ///A sequence of 'icon_size' events must be finished with a 'done' event.
            ///If the compositor has no size preferences, it must still send the
            ///'done' event, without any preceding 'icon_size' events.
            ///</summary>
 
            protected virtual void IconSize(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender, int @size)
            {
            }

            ///<summary>
            ///This event is sent after all 'icon_size' events have been sent.
            ///</summary>
 
            protected virtual void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.IconSize(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1)arguments.Sender, 
                        arguments.GetInt32(0));
                        break;
                    case 1:
                        this.Done(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1)arguments.Sender);
                        break;
                }
            }

            ///<summary>
            ///This event is sent after all 'icon_size' events have been sent.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void IconSizeDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender, int @size);
                public IconSizeDelegate? OnIconSize { get; init; }

                protected override void IconSize(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender, int @size) => OnIconSize?.Invoke(eventSender, @size);
                public delegate void DoneDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender);
                public DoneDelegate? OnDone { get; init; }

                protected override void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconManagerV1 eventSender) => OnDone?.Invoke(eventSender);
            }
        }

        private XdgToplevelIconManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static XdgToplevelIconManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (XdgToplevelIconManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///This interface defines a toplevel icon.
    ///An icon can have a name, and multiple buffers.
    ///In order to be applied, the icon must have either a name, or at least
    ///one buffer assigned. Applying an empty icon (with no buffer or name) to
    ///a toplevel should reset its icon to the default icon.
    ///
    ///It is up to compositor policy whether to prefer using a buffer or loading
    ///an icon via its name. See 'set_name' and 'add_buffer' for details.
    ///</summary>
 
    public sealed unsafe partial class XdgToplevelIconV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("xdg_toplevel_icon_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_name") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("add_buffer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlBuffer.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddError(1U, "invalid_buffer", "the provided buffer does not satisfy requirements") 
        .AddError(2U, "immutable", "the icon has already been assigned to a toplevel and must not be changed") 
        .AddError(3U, "no_buffer", "the provided buffer has been destroyed before the toplevel icon") 
        .Build() 
        , typeof(XdgToplevelIconV1), (ctx) => new XdgToplevelIconV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgToplevelIconV1.XdgToplevelIconV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroys the 'xdg_toplevel_icon_v1' object.
        ///The icon must still remain set on every toplevel it was assigned to,
        ///until the toplevel icon is reset explicitly.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///This request assigns an icon name to this icon.
        ///Any previously set name is overridden.
        ///
        ///The compositor must resolve 'icon_name' according to the lookup rules
        ///described in the XDG icon theme specification[1] using the
        ///environment's current icon theme.
        ///
        ///If the compositor does not support icon names or cannot resolve
        ///'icon_name' according to the XDG icon theme specification it must
        ///fall back to using pixel buffer data instead.
        ///
        ///If this request is made after the icon has been assigned to a toplevel
        ///via 'set_icon', an 'immutable' error must be raised.
        ///
        ///[1]: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
        ///</summary>
 
        public void SetName(string @iconName)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@iconName);
                __call.Invoke();
            }
        }

        ///<summary>
        ///This request adds pixel data supplied as wl_buffer to the icon.
        ///
        ///The client should add pixel data for all icon sizes and scales that
        ///it can provide, or which are explicitly requested by the compositor
        ///via 'icon_size' events on xdg_toplevel_icon_manager_v1.
        ///
        ///The wl_buffer supplying pixel data as 'buffer' must be backed by wl_shm
        ///and must be a square (width and height being equal).
        ///If any of these buffer requirements are not fulfilled, a 'invalid_buffer'
        ///error must be raised.
        ///
        ///If this icon instance already has a buffer of the same size and scale
        ///from a previous 'add_buffer' request, data from the last request
        ///overrides the preexisting pixel data.
        ///
        ///The wl_buffer must be kept alive for as long as the xdg_toplevel_icon
        ///it is associated with is not destroyed, otherwise a 'no_buffer' error
        ///is raised. The buffer contents must not be modified after it was
        ///assigned to the icon. As a result, the region of the wl_shm_pool's
        ///backing storage used for the wl_buffer must not be modified after this
        ///request is sent. The wl_buffer.release event is unused.
        ///
        ///If this request is made after the icon has been assigned to a toplevel
        ///via 'set_icon', an 'immutable' error must be raised.
        ///</summary>
 
        public void AddBuffer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlBuffer @buffer, int @scale)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@buffer);
                __call.Arg(@scale);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        public enum ErrorEnum
        {
            ///<summary>the provided buffer does not satisfy requirements</summary>
 
            InvalidBuffer = 1,
            ///<summary>the icon has already been assigned to a toplevel and must not be changed</summary>
 
            Immutable = 2,
            ///<summary>the provided buffer has been destroyed before the toplevel icon</summary>
 
            NoBuffer = 3
        }

        private XdgToplevelIconV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static XdgToplevelIconV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (XdgToplevelIconV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}