// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1
{
    ///<summary>
    ///The global interface exposing pointer constraining functionality. It
    ///exposes two requests: lock_pointer for locking the pointer to its
    ///position, and confine_pointer for locking the pointer to a region.
    ///
    ///The lock_pointer and confine_pointer requests create the objects
    ///wp_locked_pointer and wp_confined_pointer respectively, and the client can
    ///use these objects to interact with the lock.
    ///
    ///For any surface, only one lock or confinement may be active across all
    ///wl_pointer objects of the same seat. If a lock or confinement is requested
    ///when another lock or confinement is active or requested on the same surface
    ///and with any of the wl_pointer objects of the same seat, an
    ///'already_constrained' error will be raised.
    ///</summary>
 
    public sealed unsafe partial class ZwpPointerConstraintsV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_pointer_constraints_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("lock_pointer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion.ProxyType).AsNullable()) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("confine_pointer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion.ProxyType).AsNullable()) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddError(1U, "already_constrained", "pointer constraint already requested on that surface") 
        .Build() 
        , typeof(ZwpPointerConstraintsV1), (ctx) => new ZwpPointerConstraintsV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpPointerConstraintsV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpPointerConstraintsV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpPointerConstraintsV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Used by the client to notify the server that it will no longer use this
        ///pointer constraints object.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///The lock_pointer request lets the client request to disable movements of
        ///the virtual pointer (i.e. the cursor), effectively locking the pointer
        ///to a position. This request may not take effect immediately; in the
        ///future, when the compositor deems implementation-specific constraints
        ///are satisfied, the pointer lock will be activated and the compositor
        ///sends a locked event.
        ///
        ///The protocol provides no guarantee that the constraints are ever
        ///satisfied, and does not require the compositor to send an error if the
        ///constraints cannot ever be satisfied. It is thus possible to request a
        ///lock that will never activate.
        ///
        ///There may not be another pointer constraint of any kind requested or
        ///active on the surface for any of the wl_pointer objects of the seat of
        ///the passed pointer when requesting a lock. If there is, an error will be
        ///raised. See general pointer lock documentation for more details.
        ///
        ///The intersection of the region passed with this request and the input
        ///region of the surface is used to determine where the pointer must be
        ///in order for the lock to activate. It is up to the compositor whether to
        ///warp the pointer or require some kind of user interaction for the lock
        ///to activate. If the region is null the surface input region is used.
        ///
        ///A surface may receive pointer focus without the lock being activated.
        ///
        ///The request creates a new object wp_locked_pointer which is used to
        ///interact with the lock as well as receive updates about its state. See
        ///the the description of wp_locked_pointer for further information.
        ///
        ///Note that while a pointer is locked, the wl_pointer objects of the
        ///corresponding seat will not emit any wl_pointer.motion events, but
        ///relative motion events will still be emitted via wp_relative_pointer
        ///objects of the same seat. wl_pointer.axis and wl_pointer.button events
        ///are unaffected.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 LockPointer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer @pointer, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion? @region, LifetimeEnum @lifetime, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@surface);
                __call.Arg(@pointer);
                __call.Arg(@region);
                __call.Arg((uint)@lifetime);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///The confine_pointer request lets the client request to confine the
        ///pointer cursor to a given region. This request may not take effect
        ///immediately; in the future, when the compositor deems implementation-
        ///specific constraints are satisfied, the pointer confinement will be
        ///activated and the compositor sends a confined event.
        ///
        ///The intersection of the region passed with this request and the input
        ///region of the surface is used to determine where the pointer must be
        ///in order for the confinement to activate. It is up to the compositor
        ///whether to warp the pointer or require some kind of user interaction for
        ///the confinement to activate. If the region is null the surface input
        ///region is used.
        ///
        ///The request will create a new object wp_confined_pointer which is used
        ///to interact with the confinement as well as receive updates about its
        ///state. See the the description of wp_confined_pointer for further
        ///information.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 ConfinePointer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer @pointer, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion? @region, LifetimeEnum @lifetime, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.ArgNewId();
                __call.Arg(@surface);
                __call.Arg(@pointer);
                __call.Arg(@region);
                __call.Arg((uint)@lifetime);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        ///<summary>
        ///These errors can be emitted in response to wp_pointer_constraints
        ///requests.
        ///</summary>
 
        public enum ErrorEnum
        {
            ///<summary>pointer constraint already requested on that surface</summary>
 
            AlreadyConstrained = 1
        }

        ///<summary>
        ///These values represent different lifetime semantics. They are passed
        ///as arguments to the factory requests to specify how the constraint
        ///lifetimes should be managed.
        ///</summary>
 
        public enum LifetimeEnum
        {
            Oneshot = 1,
            Persistent = 2
        }

        private ZwpPointerConstraintsV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpPointerConstraintsV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpPointerConstraintsV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///The wp_locked_pointer interface represents a locked pointer state.
    ///
    ///While the lock of this object is active, the wl_pointer objects of the
    ///associated seat will not emit any wl_pointer.motion events.
    ///
    ///This object will send the event 'locked' when the lock is activated.
    ///Whenever the lock is activated, it is guaranteed that the locked surface
    ///will already have received pointer focus and that the pointer will be
    ///within the region passed to the request creating this object.
    ///
    ///To unlock the pointer, send the destroy request. This will also destroy
    ///the wp_locked_pointer object.
    ///
    ///If the compositor decides to unlock the pointer the unlocked event is
    ///sent. See wp_locked_pointer.unlock for details.
    ///
    ///When unlocking, the compositor may warp the cursor position to the set
    ///cursor position hint. If it does, it will not result in any relative
    ///motion events emitted via wp_relative_pointer.
    ///
    ///If the surface the lock was requested on is destroyed and the lock is not
    ///yet activated, the wp_locked_pointer object is now defunct and must be
    ///destroyed.
    ///</summary>
 
    public sealed unsafe partial class ZwpLockedPointerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_locked_pointer_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_cursor_position_hint") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_region") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion.ProxyType).AsNullable()) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("locked") 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("unlocked") 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpLockedPointerV1), (ctx) => new ZwpLockedPointerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the locked pointer object. If applicable, the compositor will
        ///unlock the pointer.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the cursor position hint relative to the top left corner of the
        ///surface.
        ///
        ///If the client is drawing its own cursor, it should update the position
        ///hint to the position of its own cursor. A compositor may use this
        ///information to warp the pointer upon unlock in order to avoid pointer
        ///jumps.
        ///
        ///The cursor position hint is double-buffered state, see
        ///wl_surface.commit.
        ///</summary>
 
        public void SetCursorPositionHint(WlFixed @surfaceX, WlFixed @surfaceY)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@surfaceX);
                __call.Arg(@surfaceY);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set a new region used to lock the pointer.
        ///
        ///The new lock region is double-buffered, see wl_surface.commit.
        ///
        ///For details about the lock region, see wp_locked_pointer.
        ///</summary>
 
        public void SetRegion(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion? @region)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@region);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Notification that the pointer lock of the seat's pointer is activated.
            ///</summary>
 
            protected virtual void Locked(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender)
            {
            }

            ///<summary>
            ///Notification that the pointer lock of the seat's pointer is no longer
            ///active. If this is a oneshot pointer lock (see
            ///wp_pointer_constraints.lifetime) this object is now defunct and should
            ///be destroyed. If this is a persistent pointer lock (see
            ///wp_pointer_constraints.lifetime) this pointer lock may again
            ///reactivate in the future.
            ///</summary>
 
            protected virtual void Unlocked(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Locked(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1)arguments.Sender);
                        break;
                    case 1:
                        this.Unlocked(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1)arguments.Sender);
                        break;
                }
            }

            ///<summary>
            ///Notification that the pointer lock of the seat's pointer is no longer
            ///active. If this is a oneshot pointer lock (see
            ///wp_pointer_constraints.lifetime) this object is now defunct and should
            ///be destroyed. If this is a persistent pointer lock (see
            ///wp_pointer_constraints.lifetime) this pointer lock may again
            ///reactivate in the future.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void LockedDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender);
                public LockedDelegate? OnLocked { get; init; }

                protected override void Locked(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender) => OnLocked?.Invoke(eventSender);
                public delegate void UnlockedDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender);
                public UnlockedDelegate? OnUnlocked { get; init; }

                protected override void Unlocked(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpLockedPointerV1 eventSender) => OnUnlocked?.Invoke(eventSender);
            }
        }

        private ZwpLockedPointerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpLockedPointerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpLockedPointerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///The wp_confined_pointer interface represents a confined pointer state.
    ///
    ///This object will send the event 'confined' when the confinement is
    ///activated. Whenever the confinement is activated, it is guaranteed that
    ///the surface the pointer is confined to will already have received pointer
    ///focus and that the pointer will be within the region passed to the request
    ///creating this object. It is up to the compositor to decide whether this
    ///requires some user interaction and if the pointer will warp to within the
    ///passed region if outside.
    ///
    ///To unconfine the pointer, send the destroy request. This will also destroy
    ///the wp_confined_pointer object.
    ///
    ///If the compositor decides to unconfine the pointer the unconfined event is
    ///sent. The wp_confined_pointer object is at this point defunct and should
    ///be destroyed.
    ///</summary>
 
    public sealed unsafe partial class ZwpConfinedPointerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_confined_pointer_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_region") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion.ProxyType).AsNullable()) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("confined") 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("unconfined") 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpConfinedPointerV1), (ctx) => new ZwpConfinedPointerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the confined pointer object. If applicable, the compositor will
        ///unconfine the pointer.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set a new region used to confine the pointer.
        ///
        ///The new confine region is double-buffered, see wl_surface.commit.
        ///
        ///If the confinement is active when the new confinement region is applied
        ///and the pointer ends up outside of newly applied region, the pointer may
        ///warped to a position within the new confinement region. If warped, a
        ///wl_pointer.motion event will be emitted, but no
        ///wp_relative_pointer.relative_motion event.
        ///
        ///The compositor may also, instead of using the new region, unconfine the
        ///pointer.
        ///
        ///For details about the confine region, see wp_confined_pointer.
        ///</summary>
 
        public void SetRegion(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegion? @region)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@region);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Notification that the pointer confinement of the seat's pointer is
            ///activated.
            ///</summary>
 
            protected virtual void Confined(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender)
            {
            }

            ///<summary>
            ///Notification that the pointer confinement of the seat's pointer is no
            ///longer active. If this is a oneshot pointer confinement (see
            ///wp_pointer_constraints.lifetime) this object is now defunct and should
            ///be destroyed. If this is a persistent pointer confinement (see
            ///wp_pointer_constraints.lifetime) this pointer confinement may again
            ///reactivate in the future.
            ///</summary>
 
            protected virtual void Unconfined(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Confined(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1)arguments.Sender);
                        break;
                    case 1:
                        this.Unconfined(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1)arguments.Sender);
                        break;
                }
            }

            ///<summary>
            ///Notification that the pointer confinement of the seat's pointer is no
            ///longer active. If this is a oneshot pointer confinement (see
            ///wp_pointer_constraints.lifetime) this object is now defunct and should
            ///be destroyed. If this is a persistent pointer confinement (see
            ///wp_pointer_constraints.lifetime) this pointer confinement may again
            ///reactivate in the future.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void ConfinedDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender);
                public ConfinedDelegate? OnConfined { get; init; }

                protected override void Confined(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender) => OnConfined?.Invoke(eventSender);
                public delegate void UnconfinedDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender);
                public UnconfinedDelegate? OnUnconfined { get; init; }

                protected override void Unconfined(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.PointerConstraintsUnstableV1.ZwpConfinedPointerV1 eventSender) => OnUnconfined?.Invoke(eventSender);
            }
        }

        private ZwpConfinedPointerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpConfinedPointerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpConfinedPointerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}