// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2
{
    ///<summary>
    ///A global interface used for exporting surfaces that can later be imported
    ///using xdg_importer.
    ///</summary>
 
    public sealed unsafe partial class ZxdgExporterV2 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_exporter_v2", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("export_toplevel") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddError(0U, "invalid_surface", "surface is not an xdg_toplevel") 
        .Build() 
        , typeof(ZxdgExporterV2), (ctx) => new ZxdgExporterV2(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExporterV2 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExporterV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExporterV2>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Notify the compositor that the xdg_exporter object will no longer be
        ///used.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///The export_toplevel request exports the passed surface so that it can later be
        ///imported via xdg_importer. When called, a new xdg_exported object will
        ///be created and xdg_exported.handle will be sent immediately. See the
        ///corresponding interface and event for details.
        ///
        ///A surface may be exported multiple times, and each exported handle may
        ///be used to create an xdg_imported multiple times. Only xdg_toplevel
        ///equivalent surfaces may be exported, otherwise an invalid_surface
        ///protocol error is sent.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2 ExportToplevel(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@surface);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        ///<summary>
        ///These errors can be emitted in response to invalid xdg_exporter
        ///requests.
        ///</summary>
 
        public enum ErrorEnum
        {
            ///<summary>surface is not an xdg_toplevel</summary>
 
            InvalidSurface = 0
        }

        private ZxdgExporterV2(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgExporterV2 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgExporterV2)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///A global interface used for importing surfaces exported by xdg_exporter.
    ///With this interface, a client can create a reference to a surface of
    ///another client.
    ///</summary>
 
    public sealed unsafe partial class ZxdgImporterV2 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_importer_v2", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("import_toplevel") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZxdgImporterV2), (ctx) => new ZxdgImporterV2(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImporterV2 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImporterV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImporterV2>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Notify the compositor that the xdg_importer object will no longer be
        ///used.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///The import_toplevel request imports a surface from any client given a handle
        ///retrieved by exporting said surface using xdg_exporter.export_toplevel.
        ///When called, a new xdg_imported object will be created. This new object
        ///represents the imported surface, and the importing client can
        ///manipulate its relationship using it. See xdg_imported for details.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2 ImportToplevel(string @handle, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@handle);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private ZxdgImporterV2(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgImporterV2 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgImporterV2)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///An xdg_exported object represents an exported reference to a surface. The
    ///exported surface may be referenced as long as the xdg_exported object not
    ///destroyed. Destroying the xdg_exported invalidates any relationship the
    ///importer may have established using xdg_imported.
    ///</summary>
 
    public sealed unsafe partial class ZxdgExportedV2 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_exported_v2", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("handle") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZxdgExportedV2), (ctx) => new ZxdgExportedV2(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Revoke the previously exported surface. This invalidates any
        ///relationship the importer may have set up using the xdg_imported created
        ///given the handle sent via xdg_exported.handle.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///The handle event contains the unique handle of this exported surface
            ///reference. It may be shared with any client, which then can use it to
            ///import the surface by calling xdg_importer.import_toplevel. A handle
            ///may be used to import the surface multiple times.
            ///</summary>
 
            protected virtual void Handle(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2 eventSender, string @handle)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Handle(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2)arguments.Sender, 
                        arguments.GetString(0)!);
                        break;
                }
            }

            ///<summary>
            ///The handle event contains the unique handle of this exported surface
            ///reference. It may be shared with any client, which then can use it to
            ///import the surface by calling xdg_importer.import_toplevel. A handle
            ///may be used to import the surface multiple times.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void HandleDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2 eventSender, string @handle);
                public HandleDelegate? OnHandle { get; init; }

                protected override void Handle(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgExportedV2 eventSender, string @handle) => OnHandle?.Invoke(eventSender, @handle);
            }
        }

        private ZxdgExportedV2(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgExportedV2 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgExportedV2)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///An xdg_imported object represents an imported reference to surface exported
    ///by some client. A client can use this interface to manipulate
    ///relationships between its own surfaces and the imported surface.
    ///</summary>
 
    public sealed unsafe partial class ZxdgImportedV2 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_imported_v2", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_parent_of") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroyed") 
        .Build() 
        ) 
        .AddError(0U, "invalid_surface", "surface is not an xdg_toplevel") 
        .Build() 
        , typeof(ZxdgImportedV2), (ctx) => new ZxdgImportedV2(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Notify the compositor that it will no longer use the xdg_imported
        ///object. Any relationship that may have been set up will at this point
        ///be invalidated.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the imported surface as the parent of some surface of the client.
        ///The passed surface must be an xdg_toplevel equivalent, otherwise an
        ///invalid_surface protocol error is sent. Calling this function sets up
        ///a surface to surface relation with the same stacking and positioning
        ///semantics as xdg_toplevel.set_parent.
        ///</summary>
 
        public void SetParentOf(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@surface);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///The imported surface handle has been destroyed and any relationship set
            ///up has been invalidated. This may happen for various reasons, for
            ///example if the exported surface or the exported surface handle has been
            ///destroyed, if the handle used for importing was invalid.
            ///</summary>
 
            protected virtual void Destroyed(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2 eventSender)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Destroyed(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2)arguments.Sender);
                        break;
                }
            }

            ///<summary>
            ///The imported surface handle has been destroyed and any relationship set
            ///up has been invalidated. This may happen for various reasons, for
            ///example if the exported surface or the exported surface handle has been
            ///destroyed, if the handle used for importing was invalid.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void DestroyedDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2 eventSender);
                public DestroyedDelegate? OnDestroyed { get; init; }

                protected override void Destroyed(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgForeignUnstableV2.ZxdgImportedV2 eventSender) => OnDestroyed?.Invoke(eventSender);
            }
        }

        ///<summary>
        ///These errors can be emitted in response to invalid xdg_imported
        ///requests.
        ///</summary>
 
        public enum ErrorEnum
        {
            ///<summary>surface is not an xdg_toplevel</summary>
 
            InvalidSurface = 0
        }

        private ZxdgImportedV2(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgImportedV2 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgImportedV2)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}