// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1
{
    ///<summary>
    ///This global offers an alternative, optional way to set cursor images. This
    ///new way uses enumerated cursors instead of a wl_surface like
    ///wl_pointer.set_cursor does.
    ///
    ///Warning! The protocol described in this file is currently in the testing
    ///phase. Backward compatible changes may be added together with the
    ///corresponding interface version bump. Backward incompatible changes can
    ///only be done by creating a new major version of the extension.
    ///</summary>
 
    public sealed unsafe partial class WpCursorShapeManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_cursor_shape_manager_v1", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_pointer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_tablet_tool_v2") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TabletV2.ZwpTabletToolV2.ProxyType)) 
        .Build() 
        ) 
        .Build() 
        , typeof(WpCursorShapeManagerV1), (ctx) => new WpCursorShapeManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the cursor shape manager.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Obtain a wp_cursor_shape_device_v1 for a wl_pointer object.
        ///
        ///When the pointer capability is removed from the wl_seat, the
        ///wp_cursor_shape_device_v1 object becomes inert.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1 GetPointer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer @pointer, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@pointer);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///Obtain a wp_cursor_shape_device_v1 for a zwp_tablet_tool_v2 object.
        ///
        ///When the zwp_tablet_tool_v2 is removed, the wp_cursor_shape_device_v1
        ///object becomes inert.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1 GetTabletToolV2(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TabletV2.ZwpTabletToolV2 @tabletTool, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.ArgNewId();
                __call.Arg(@tabletTool);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private WpCursorShapeManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpCursorShapeManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpCursorShapeManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///This interface allows clients to set the cursor shape.
    ///</summary>
 
    public sealed unsafe partial class WpCursorShapeDeviceV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_cursor_shape_device_v1", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_shape") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddError(1U, "invalid_shape", "the specified shape value is invalid") 
        .Build() 
        , typeof(WpCursorShapeDeviceV1), (ctx) => new WpCursorShapeDeviceV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.CursorShapeV1.WpCursorShapeDeviceV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the cursor shape device.
        ///
        ///The device cursor shape remains unchanged.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Sets the device cursor to the specified shape. The compositor will
        ///change the cursor image based on the specified shape.
        ///
        ///The cursor actually changes only if the input device focus is one of
        ///the requesting client's surfaces. If any, the previous cursor image
        ///(surface or shape) is replaced.
        ///
        ///The "shape" argument must be a valid enum entry, otherwise the
        ///invalid_shape protocol error is raised.
        ///
        ///This is similar to the wl_pointer.set_cursor and
        ///zwp_tablet_tool_v2.set_cursor requests, but this request accepts a
        ///shape instead of contents in the form of a surface. Clients can mix
        ///set_cursor and set_shape requests.
        ///
        ///The serial parameter must match the latest wl_pointer.enter or
        ///zwp_tablet_tool_v2.proximity_in serial number sent to the client.
        ///Otherwise the request will be ignored.
        ///</summary>
 
        public void SetShape(uint @serial, ShapeEnum @shape)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@serial);
                __call.Arg((uint)@shape);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        ///<summary>
        ///This enum describes cursor shapes.
        ///
        ///The names are taken from the CSS W3C specification:
        ///https://w3c.github.io/csswg-drafts/css-ui/#cursor
        ///with a few additions.
        ///
        ///Note that there are some groups of cursor shapes that are related:
        ///The first group is drag-and-drop cursors which are used to indicate
        ///the selected action during dnd operations. The second group is resize
        ///cursors which are used to indicate resizing and moving possibilities
        ///on window borders. It is recommended that the shapes in these groups
        ///should use visually compatible images and metaphors.
        ///</summary>
 
        public enum ShapeEnum
        {
            ///<summary>default cursor</summary>
 
            Default = 1,
            ///<summary>a context menu is available for the object under the cursor</summary>
 
            ContextMenu = 2,
            ///<summary>help is available for the object under the cursor</summary>
 
            Help = 3,
            ///<summary>pointer that indicates a link or another interactive element</summary>
 
            Pointer = 4,
            ///<summary>progress indicator</summary>
 
            Progress = 5,
            ///<summary>program is busy, user should wait</summary>
 
            Wait = 6,
            ///<summary>a cell or set of cells may be selected</summary>
 
            Cell = 7,
            ///<summary>simple crosshair</summary>
 
            Crosshair = 8,
            ///<summary>text may be selected</summary>
 
            Text = 9,
            ///<summary>vertical text may be selected</summary>
 
            VerticalText = 10,
            ///<summary>drag-and-drop: alias of/shortcut to something is to be created</summary>
 
            Alias = 11,
            ///<summary>drag-and-drop: something is to be copied</summary>
 
            Copy = 12,
            ///<summary>drag-and-drop: something is to be moved</summary>
 
            Move = 13,
            ///<summary>drag-and-drop: the dragged item cannot be dropped at the current cursor location</summary>
 
            NoDrop = 14,
            ///<summary>drag-and-drop: the requested action will not be carried out</summary>
 
            NotAllowed = 15,
            ///<summary>drag-and-drop: something can be grabbed</summary>
 
            Grab = 16,
            ///<summary>drag-and-drop: something is being grabbed</summary>
 
            Grabbing = 17,
            ///<summary>resizing: the east border is to be moved</summary>
 
            EResize = 18,
            ///<summary>resizing: the north border is to be moved</summary>
 
            NResize = 19,
            ///<summary>resizing: the north-east corner is to be moved</summary>
 
            NeResize = 20,
            ///<summary>resizing: the north-west corner is to be moved</summary>
 
            NwResize = 21,
            ///<summary>resizing: the south border is to be moved</summary>
 
            SResize = 22,
            ///<summary>resizing: the south-east corner is to be moved</summary>
 
            SeResize = 23,
            ///<summary>resizing: the south-west corner is to be moved</summary>
 
            SwResize = 24,
            ///<summary>resizing: the west border is to be moved</summary>
 
            WResize = 25,
            ///<summary>resizing: the east and west borders are to be moved</summary>
 
            EwResize = 26,
            ///<summary>resizing: the north and south borders are to be moved</summary>
 
            NsResize = 27,
            ///<summary>resizing: the north-east and south-west corners are to be moved</summary>
 
            NeswResize = 28,
            ///<summary>resizing: the north-west and south-east corners are to be moved</summary>
 
            NwseResize = 29,
            ///<summary>resizing: that the item/column can be resized horizontally</summary>
 
            ColResize = 30,
            ///<summary>resizing: that the item/row can be resized vertically</summary>
 
            RowResize = 31,
            ///<summary>something can be scrolled in any direction</summary>
 
            AllScroll = 32,
            ///<summary>something can be zoomed in</summary>
 
            ZoomIn = 33,
            ///<summary>something can be zoomed out</summary>
 
            ZoomOut = 34,
            ///<summary>drag-and-drop: the user will select which action will be carried out (non-css value)</summary>
 
            DndAsk = 35,
            ///<summary>resizing: something can be moved or resized in any direction (non-css value)</summary>
 
            AllResize = 36
        }

        public enum ErrorEnum
        {
            ///<summary>the specified shape value is invalid</summary>
 
            InvalidShape = 1
        }

        private WpCursorShapeDeviceV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpCursorShapeDeviceV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpCursorShapeDeviceV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}