// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1
{
    ///<summary>
    ///This interface allows a compositor to announce support for server-side
    ///decorations.
    ///
    ///A window decoration is a set of window controls as deemed appropriate by
    ///the party managing them, such as user interface components used to move,
    ///resize and change a window's state.
    ///
    ///A client can use this protocol to request being decorated by a supporting
    ///compositor.
    ///
    ///If compositor and client do not negotiate the use of a server-side
    ///decoration using this protocol, clients continue to self-decorate as they
    ///see fit.
    ///
    ///Warning! The protocol described in this file is experimental and
    ///backward incompatible changes may be made. Backward compatible changes
    ///may be added together with the corresponding interface version bump.
    ///Backward incompatible changes are done by bumping the version number in
    ///the protocol and interface names and resetting the interface version.
    ///Once the protocol is to be declared stable, the 'z' prefix and the
    ///version number in the protocol and interface names are removed and the
    ///interface version number is reset.
    ///</summary>
 
    public sealed unsafe partial class ZxdgDecorationManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_decoration_manager_v1", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_toplevel_decoration") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgShell.XdgToplevel.ProxyType)) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZxdgDecorationManagerV1), (ctx) => new ZxdgDecorationManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgDecorationManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgDecorationManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgDecorationManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the decoration manager. This doesn't destroy objects created
        ///with the manager.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Create a new decoration object associated with the given toplevel.
        ///
        ///For objects of version 1, creating an xdg_toplevel_decoration from an
        ///xdg_toplevel which has a buffer attached or committed is a client
        ///error, and any attempts by a client to attach or manipulate a buffer
        ///prior to the first xdg_toplevel_decoration.configure event must also be
        ///treated as errors.
        ///
        ///For objects of version 2 or newer, creating an xdg_toplevel_decoration
        ///from an xdg_toplevel which has a buffer attached or committed is
        ///allowed. The initial decoration mode of the surface if a buffer is
        ///already attached depends on whether a xdg_toplevel_decoration object
        ///has been associated with the surface or not prior to this request.
        ///
        ///If an xdg_toplevel_decoration was associated with the surface, then
        ///destroyed without a surface commit, the previous decoration mode is
        ///retained.
        ///
        ///If no xdg_toplevel_decoration was associated with the surface prior to
        ///this request, or if a surface commit has been performed after a previous
        ///xdg_toplevel_decoration object associated with the surface was
        ///destroyed, the decoration mode is assumed to be client-side.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1 GetToplevelDecoration(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgShell.XdgToplevel @toplevel, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@toplevel);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private ZxdgDecorationManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgDecorationManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgDecorationManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///The decoration object allows the compositor to toggle server-side window
    ///decorations for a toplevel surface. The client can request to switch to
    ///another mode.
    ///
    ///The xdg_toplevel_decoration object must be destroyed before its
    ///xdg_toplevel.
    ///</summary>
 
    public sealed unsafe partial class ZxdgToplevelDecorationV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zxdg_toplevel_decoration_v1", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_mode") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("unset_mode") 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("configure") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddError(0U, "unconfigured_buffer", "xdg_toplevel has a buffer attached before configure") 
        .AddError(1U, "already_constructed", "xdg_toplevel already has a decoration object") 
        .AddError(2U, "orphaned", "xdg_toplevel destroyed before the decoration object") 
        .AddError(3U, "invalid_mode", "invalid mode") 
        .Build() 
        , typeof(ZxdgToplevelDecorationV1), (ctx) => new ZxdgToplevelDecorationV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Switch back to a mode without any server-side decorations at the next
        ///commit, unless a new xdg_toplevel_decoration is created for the surface
        ///first.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the toplevel surface decoration mode. This informs the compositor
        ///that the client prefers the provided decoration mode.
        ///
        ///After requesting a decoration mode, the compositor will respond by
        ///emitting an xdg_surface.configure event. The client should then update
        ///its content, drawing it without decorations if the received mode is
        ///server-side decorations. The client must also acknowledge the configure
        ///when committing the new content (see xdg_surface.ack_configure).
        ///
        ///The compositor can decide not to use the client's mode and enforce a
        ///different mode instead.
        ///
        ///Clients whose decoration mode depend on the xdg_toplevel state may send
        ///a set_mode request in response to an xdg_surface.configure event and wait
        ///for the next xdg_surface.configure event to prevent unwanted state.
        ///Such clients are responsible for preventing configure loops and must
        ///make sure not to send multiple successive set_mode requests with the
        ///same decoration mode.
        ///
        ///If an invalid mode is supplied by the client, the invalid_mode protocol
        ///error is raised by the compositor.
        ///</summary>
 
        public void SetMode(ModeEnum @mode)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg((uint)@mode);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Unset the toplevel surface decoration mode. This informs the compositor
        ///that the client doesn't prefer a particular decoration mode.
        ///
        ///This request has the same semantics as set_mode.
        ///</summary>
 
        public void UnsetMode()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///The configure event configures the effective decoration mode. The
            ///configured state should not be applied immediately. Clients must send an
            ///ack_configure in response to this event. See xdg_surface.configure and
            ///xdg_surface.ack_configure for details.
            ///
            ///A configure event can be sent at any time. The specified mode must be
            ///obeyed by the client.
            ///</summary>
 
            protected virtual void Configure(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1 eventSender, ModeEnum @mode)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Configure(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1)arguments.Sender, (ModeEnum)
                        arguments.GetUInt32(0));
                        break;
                }
            }

            ///<summary>
            ///The configure event configures the effective decoration mode. The
            ///configured state should not be applied immediately. Clients must send an
            ///ack_configure in response to this event. See xdg_surface.configure and
            ///xdg_surface.ack_configure for details.
            ///
            ///A configure event can be sent at any time. The specified mode must be
            ///obeyed by the client.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void ConfigureDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1 eventSender, ModeEnum @mode);
                public ConfigureDelegate? OnConfigure { get; init; }

                protected override void Configure(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgDecorationUnstableV1.ZxdgToplevelDecorationV1 eventSender, ModeEnum @mode) => OnConfigure?.Invoke(eventSender, @mode);
            }
        }

        public enum ErrorEnum
        {
            ///<summary>xdg_toplevel has a buffer attached before configure</summary>
 
            UnconfiguredBuffer = 0,
            ///<summary>xdg_toplevel already has a decoration object</summary>
 
            AlreadyConstructed = 1,
            ///<summary>xdg_toplevel destroyed before the decoration object</summary>
 
            Orphaned = 2,
            ///<summary>invalid mode</summary>
 
            InvalidMode = 3
        }

        ///<summary>
        ///These values describe window decoration modes.
        ///</summary>
 
        public enum ModeEnum
        {
            ///<summary>no server-side window decoration</summary>
 
            ClientSide = 1,
            ///<summary>server-side window decoration</summary>
 
            ServerSide = 2
        }

        private ZxdgToplevelDecorationV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZxdgToplevelDecorationV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZxdgToplevelDecorationV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}