// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter
{
    ///<summary>
    ///The global interface exposing surface cropping and scaling
    ///capabilities is used to instantiate an interface extension for a
    ///wl_surface object. This extended interface will then allow
    ///cropping and scaling the surface contents, effectively
    ///disconnecting the direct relationship between the buffer and the
    ///surface size.
    ///</summary>
 
    public sealed unsafe partial class WpViewporter : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_viewporter", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_viewport") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddError(0U, "viewport_exists", "the surface already has a viewport object associated") 
        .Build() 
        , typeof(WpViewporter), (ctx) => new WpViewporter(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewporter Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewporter.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewporter>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Informs the server that the client will not be using this
        ///protocol object anymore. This does not affect any other objects,
        ///wp_viewport objects included.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Instantiate an interface extension for the given wl_surface to
        ///crop and scale its content. If the given wl_surface already has
        ///a wp_viewport object associated, the viewport_exists
        ///protocol error is raised.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport GetViewport(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@surface);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        public enum ErrorEnum
        {
            ///<summary>the surface already has a viewport object associated</summary>
 
            ViewportExists = 0
        }

        private WpViewporter(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpViewporter Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpViewporter)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///An additional interface to a wl_surface object, which allows the
    ///client to specify the cropping and scaling of the surface
    ///contents.
    ///
    ///This interface works with two concepts: the source rectangle (src_x,
    ///src_y, src_width, src_height), and the destination size (dst_width,
    ///dst_height). The contents of the source rectangle are scaled to the
    ///destination size, and content outside the source rectangle is ignored.
    ///This state is double-buffered, see wl_surface.commit.
    ///
    ///The two parts of crop and scale state are independent: the source
    ///rectangle, and the destination size. Initially both are unset, that
    ///is, no scaling is applied. The whole of the current wl_buffer is
    ///used as the source, and the surface size is as defined in
    ///wl_surface.attach.
    ///
    ///If the destination size is set, it causes the surface size to become
    ///dst_width, dst_height. The source (rectangle) is scaled to exactly
    ///this size. This overrides whatever the attached wl_buffer size is,
    ///unless the wl_buffer is NULL. If the wl_buffer is NULL, the surface
    ///has no content and therefore no size. Otherwise, the size is always
    ///at least 1x1 in surface local coordinates.
    ///
    ///If the source rectangle is set, it defines what area of the wl_buffer is
    ///taken as the source. If the source rectangle is set and the destination
    ///size is not set, then src_width and src_height must be integers, and the
    ///surface size becomes the source rectangle size. This results in cropping
    ///without scaling. If src_width or src_height are not integers and
    ///destination size is not set, the bad_size protocol error is raised when
    ///the surface state is applied.
    ///
    ///The coordinate transformations from buffer pixel coordinates up to
    ///the surface-local coordinates happen in the following order:
    ///1. buffer_transform (wl_surface.set_buffer_transform)
    ///2. buffer_scale (wl_surface.set_buffer_scale)
    ///3. crop and scale (wp_viewport.set*)
    ///This means, that the source rectangle coordinates of crop and scale
    ///are given in the coordinates after the buffer transform and scale,
    ///i.e. in the coordinates that would be the surface-local coordinates
    ///if the crop and scale was not applied.
    ///
    ///If src_x or src_y are negative, the bad_value protocol error is raised.
    ///Otherwise, if the source rectangle is partially or completely outside of
    ///the non-NULL wl_buffer, then the out_of_buffer protocol error is raised
    ///when the surface state is applied. A NULL wl_buffer does not raise the
    ///out_of_buffer error.
    ///
    ///If the wl_surface associated with the wp_viewport is destroyed,
    ///all wp_viewport requests except 'destroy' raise the protocol error
    ///no_surface.
    ///
    ///If the wp_viewport object is destroyed, the crop and scale
    ///state is removed from the wl_surface. The change will be applied
    ///on the next wl_surface.commit.
    ///</summary>
 
    public sealed unsafe partial class WpViewport : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_viewport", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_source") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_destination") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddError(0U, "bad_value", "negative or zero values in width or height") 
        .AddError(1U, "bad_size", "destination size is not integer") 
        .AddError(2U, "out_of_buffer", "source rectangle extends outside of the content area") 
        .AddError(3U, "no_surface", "the wl_surface was destroyed") 
        .Build() 
        , typeof(WpViewport), (ctx) => new WpViewport(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Viewporter.WpViewport>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///The associated wl_surface's crop and scale state is removed.
        ///The change is applied on the next wl_surface.commit.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the source rectangle of the associated wl_surface. See
        ///wp_viewport for the description, and relation to the wl_buffer
        ///size.
        ///
        ///If all of x, y, width and height are -1.0, the source rectangle is
        ///unset instead. Any other set of values where width or height are zero
        ///or negative, or x or y are negative, raise the bad_value protocol
        ///error.
        ///
        ///The crop and scale state is double-buffered, see wl_surface.commit.
        ///</summary>
 
        public void SetSource(WlFixed @x, WlFixed @y, WlFixed @width, WlFixed @height)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@x);
                __call.Arg(@y);
                __call.Arg(@width);
                __call.Arg(@height);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the destination size of the associated wl_surface. See
        ///wp_viewport for the description, and relation to the wl_buffer
        ///size.
        ///
        ///If width is -1 and height is -1, the destination size is unset
        ///instead. Any other pair of values for width and height that
        ///contains zero or negative values raises the bad_value protocol
        ///error.
        ///
        ///The crop and scale state is double-buffered, see wl_surface.commit.
        ///</summary>
 
        public void SetDestination(int @width, int @height)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@width);
                __call.Arg(@height);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        public enum ErrorEnum
        {
            ///<summary>negative or zero values in width or height</summary>
 
            BadValue = 0,
            ///<summary>destination size is not integer</summary>
 
            BadSize = 1,
            ///<summary>source rectangle extends outside of the content area</summary>
 
            OutOfBuffer = 2,
            ///<summary>the wl_surface was destroyed</summary>
 
            NoSurface = 3
        }

        private WpViewport(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpViewport Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpViewport)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}