// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3
{
    ///<summary>
    ///The zwp_text_input_v3 interface represents text input and input methods
    ///associated with a seat. It provides enter/leave events to follow the
    ///text input focus for a seat.
    ///
    ///Requests are used to enable/disable the text-input object and set
    ///state information like surrounding and selected text or the content type.
    ///The information about the entered text is sent to the text-input object
    ///via the preedit_string and commit_string events.
    ///
    ///Text is valid UTF-8 encoded, indices and lengths are in bytes. Indices
    ///must not point to middle bytes inside a code point: they must either
    ///point to the first byte of a code point or to the end of the buffer.
    ///Lengths must be measured between two valid indices.
    ///
    ///Focus moving throughout surfaces will result in the emission of
    ///zwp_text_input_v3.enter and zwp_text_input_v3.leave events. The focused
    ///surface must commit zwp_text_input_v3.enable and
    ///zwp_text_input_v3.disable requests as the keyboard focus moves across
    ///editable and non-editable elements of the UI. Those two requests are not
    ///expected to be paired with each other, the compositor must be able to
    ///handle consecutive series of the same request.
    ///
    ///State is sent by the state requests (set_surrounding_text,
    ///set_content_type and set_cursor_rectangle) and a commit request. After an
    ///enter event or disable request all state information is invalidated and
    ///needs to be resent by the client.
    ///</summary>
 
    public sealed unsafe partial class ZwpTextInputV3 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_text_input_v3", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("enable") 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("disable") 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_surrounding_text") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_text_change_cause") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_content_type") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_cursor_rectangle") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("commit") 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_available_actions") 
        .SinceVersion(2) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Array) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("show_input_panel") 
        .SinceVersion(2) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("hide_input_panel") 
        .SinceVersion(2) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("enter") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("leave") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("preedit_string") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String.AsNullable()) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Int32) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("commit_string") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String.AsNullable()) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("delete_surrounding_text") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("done") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("action") 
        .SinceVersion(2) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("language") 
        .SinceVersion(2) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("preedit_hint") 
        .SinceVersion(2) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .AddError(0U, "invalid_action", "an invalid or duplicate action was specified") 
        .Build() 
        , typeof(ZwpTextInputV3), (ctx) => new ZwpTextInputV3(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the wp_text_input object. Also disables all surfaces enabled
        ///through this wp_text_input object.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Requests text input on the surface previously obtained from the enter
        ///event.
        ///
        ///This request must be issued every time the focused text input changes
        ///to a new one, including within the current surface. Use
        ///zwp_text_input_v3.disable when there is no longer any input focus on
        ///the current surface.
        ///
        ///Clients must not enable more than one text input on the single seat
        ///and should disable the current text input before enabling the new one.
        ///Requests to enable a text input when another text input is enabled
        ///on the same seat must be ignored by compositor.
        ///
        ///This request resets all state associated with previous enable, disable,
        ///set_surrounding_text, set_text_change_cause, set_content_type, and
        ///set_cursor_rectangle requests, as well as the state associated with
        ///preedit_string, commit_string, and delete_surrounding_text events.
        ///
        ///The set_surrounding_text, set_content_type and set_cursor_rectangle
        ///requests must follow if the text input supports the necessary
        ///functionality.
        ///
        ///State set with this request is double-buffered. It will get applied on
        ///the next zwp_text_input_v3.commit request, and stay valid until the
        ///next committed enable or disable request.
        ///
        ///The changes must be applied by the compositor after issuing a
        ///zwp_text_input_v3.commit request.
        ///</summary>
 
        public void Enable()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Explicitly disable text input on the current surface (typically when
        ///there is no focus on any text entry inside the surface).
        ///
        ///State set with this request is double-buffered. It will get applied on
        ///the next zwp_text_input_v3.commit request.
        ///</summary>
 
        public void Disable()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Sets the surrounding plain text around the input, excluding the preedit
        ///text.
        ///
        ///The client should notify the compositor of any changes in any of the
        ///values carried with this request, including changes caused by handling
        ///incoming text-input events as well as changes caused by other
        ///mechanisms like keyboard typing.
        ///
        ///If the client is unaware of the text around the cursor, it should not
        ///issue this request, to signify lack of support to the compositor.
        ///
        ///Text is UTF-8 encoded, and should include the cursor position, the
        ///complete selection and additional characters before and after them.
        ///There is a maximum length of wayland messages, so text can not be
        ///longer than 4000 bytes.
        ///
        ///Cursor is the byte offset of the cursor within text buffer.
        ///
        ///Anchor is the byte offset of the selection anchor within text buffer.
        ///If there is no selected text, anchor is the same as cursor.
        ///
        ///If any preedit text is present, it is replaced with a cursor for the
        ///purpose of this event.
        ///
        ///Values set with this request are double-buffered. They will get applied
        ///on the next zwp_text_input_v3.commit request, and stay valid until the
        ///next committed enable or disable request.
        ///
        ///The initial state for affected fields is empty, meaning that the text
        ///input does not support sending surrounding text. If the empty values
        ///get applied, subsequent attempts to change them may have no effect.
        ///</summary>
 
        public void SetSurroundingText(string @text, int @cursor, int @anchor)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 3))
            {
                __call.Arg(@text);
                __call.Arg(@cursor);
                __call.Arg(@anchor);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Tells the compositor why the text surrounding the cursor changed.
        ///
        ///Whenever the client detects an external change in text, cursor, or
        ///anchor posision, it must issue this request to the compositor. This
        ///request is intended to give the input method a chance to update the
        ///preedit text in an appropriate way, e.g. by removing it when the user
        ///starts typing with a keyboard.
        ///
        ///cause describes the source of the change.
        ///
        ///The value set with this request is double-buffered. It must be applied
        ///and reset to initial at the next zwp_text_input_v3.commit request.
        ///
        ///The initial value of cause is input_method.
        ///</summary>
 
        public void SetTextChangeCause(ChangeCauseEnum @cause)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 4))
            {
                __call.Arg((uint)@cause);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Sets the content purpose and content hint. While the purpose is the
        ///basic purpose of an input field, the hint flags allow to modify some of
        ///the behavior.
        ///
        ///Values set with this request are double-buffered. They will get applied
        ///on the next zwp_text_input_v3.commit request.
        ///Subsequent attempts to update them may have no effect. The values
        ///remain valid until the next committed enable or disable request.
        ///
        ///The initial value for hint is none, and the initial value for purpose
        ///is normal.
        ///</summary>
 
        public void SetContentType(ContentHintEnum @hint, ContentPurposeEnum @purpose)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 5))
            {
                __call.Arg((uint)@hint);
                __call.Arg((uint)@purpose);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Marks an area around the cursor as a x, y, width, height rectangle in
        ///surface local coordinates.
        ///
        ///Allows the compositor to put a window with word suggestions near the
        ///cursor, without obstructing the text being input.
        ///
        ///If the client is unaware of the position of edited text, it should not
        ///issue this request, to signify lack of support to the compositor.
        ///
        ///Values set with this request are double-buffered. They will get applied
        ///on the next zwp_text_input_v3.commit request, and stay valid until the
        ///next committed enable or disable request.
        ///
        ///The initial values describing a cursor rectangle are empty. That means
        ///the text input does not support describing the cursor area. If the
        ///empty values get applied, subsequent attempts to change them may have
        ///no effect.
        ///
        ///As of version 2, the zwp_text_input_v3.commit request does not apply
        ///values sent with this request. Instead, it stores them in a separate
        ///"committed" area. The committed values, if still valid, get applied on
        ///the next wl_surface.commit request on the surface with text-input focus.
        ///Both committed and applied values get invalidated on:
        ///
        ///- the next committed enable or disable request, or
        ///- a change of the focused surface of the text-input (leave or enter events).
        ///
        ///This double stage application allows the compositor to position
        ///the input method popup in the same frame as the contents
        ///of the text on the surface are updated.
        ///</summary>
 
        public void SetCursorRectangle(int @x, int @y, int @width, int @height)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 6))
            {
                __call.Arg(@x);
                __call.Arg(@y);
                __call.Arg(@width);
                __call.Arg(@height);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Atomically applies state changes recently sent to the compositor.
        ///
        ///The commit request establishes and updates the state of the client, and
        ///must be issued after any changes to apply them.
        ///
        ///Text input state (enabled status, content purpose, content hint,
        ///surrounding text and change cause, cursor rectangle) is conceptually
        ///double-buffered within the context of a text input, i.e. between a
        ///committed enable request and the following committed enable or disable
        ///request.
        ///
        ///Protocol requests modify the pending state, as opposed to the current
        ///state in use by the input method. A commit request atomically applies
        ///all pending state, replacing the current state. After commit, the new
        ///pending state is as documented for each related request.
        ///
        ///Requests are applied in the order of arrival.
        ///
        ///Neither current nor pending state are modified unless noted otherwise.
        ///
        ///The compositor must count the number of commit requests coming from
        ///each zwp_text_input_v3 object and use the count as the serial in done
        ///events.
        ///</summary>
 
        public void Commit()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 7))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Set the actions available for this text input.
        ///
        ///Values set with this request are double-buffered. They will get applied
        ///on the next zwp_text_input_v3.commit request.
        ///
        ///If the available_actions array contains the none action, or contains the
        ///same action multiple times, the compositor must raise the invalid_action
        ///protocol error.
        ///
        ///Initially, no actions are available.
        ///</summary>
 
        public void SetAvailableActions(System.ReadOnlySpan<byte> @availableActions)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 8))
            {
                __call.Arg(@availableActions);
                __call.Invoke();
            }
        }

        public bool IsSetAvailableActionsAvailable => Version >= 2;
        ///<summary>
        ///Requests an input panel to be shown (e.g. a on-screen keyboard).
        ///
        ///This request only hints the desired interaction pattern from the
        ///client side, and its effect may be ignored by compositors given
        ///other environmental factors. Repeated calls will be ignored.
        ///</summary>
 
        public void ShowInputPanel()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 9))
            {
                __call.Invoke();
            }
        }

        public bool IsShowInputPanelAvailable => Version >= 2;
        ///<summary>
        ///Requests an input panel to be hidden.
        ///
        ///This request only hints the desired interaction pattern from the
        ///client side, and its effect may be ignored by compositors given
        ///other environmental factors. Repeated calls will be ignored.
        ///</summary>
 
        public void HideInputPanel()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 10))
            {
                __call.Invoke();
            }
        }

        public bool IsHideInputPanelAvailable => Version >= 2;
        public bool IsActionEventAvailable => Version >= 2;
        public bool IsLanguageEventAvailable => Version >= 2;
        public bool IsPreeditHintEventAvailable => Version >= 2;
        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Notification that this seat's text-input focus is on a certain surface.
            ///
            ///If client has created multiple text input objects, compositor must send
            ///this event to all of them.
            ///
            ///When the seat has the keyboard capability the text-input focus follows
            ///the keyboard focus. This event sets the current surface for the
            ///text-input object.
            ///</summary>
 
            protected virtual void Enter(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface)
            {
            }

            ///<summary>
            ///Notification that this seat's text-input focus is no longer on a
            ///certain surface. The client should reset any preedit string previously
            ///set.
            ///
            ///The leave notification clears the current surface. It is sent before
            ///the enter notification for the new focus. After leave event, compositor
            ///must ignore requests from any text input instances until next enter
            ///event.
            ///
            ///When the seat has the keyboard capability the text-input focus follows
            ///the keyboard focus.
            ///</summary>
 
            protected virtual void Leave(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface)
            {
            }

            ///<summary>
            ///Notify when a new composing text (pre-edit) should be set at the
            ///current cursor position. Any previously set composing text must be
            ///removed. Any previously existing selected text must be removed.
            ///
            ///The argument text contains the pre-edit string buffer.
            ///
            ///The parameters cursor_begin and cursor_end are counted in bytes
            ///relative to the beginning of the submitted text buffer. Cursor should
            ///be hidden when both are equal to -1.
            ///
            ///They could be represented by the client as a line if both values are
            ///the same, or as a text highlight otherwise.
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset to initial on the next zwp_text_input_v3.done event.
            ///
            ///The initial value of text is an empty string, and cursor_begin,
            ///cursor_end and cursor_hidden are all 0.
            ///</summary>
 
            protected virtual void PreeditString(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text, int @cursorBegin, int @cursorEnd)
            {
            }

            ///<summary>
            ///Notify when text should be inserted into the editor widget. The text to
            ///commit could be either just a single character after a key press or the
            ///result of some composing (pre-edit).
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset to initial on the next zwp_text_input_v3.done event.
            ///
            ///The initial value of text is an empty string.
            ///</summary>
 
            protected virtual void CommitString(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text)
            {
            }

            ///<summary>
            ///Notify when the text around the current cursor position should be
            ///deleted.
            ///
            ///Before_length and after_length are the number of bytes before and after
            ///the current cursor index (excluding the selection) to delete.
            ///
            ///If a preedit text is present, in effect before_length is counted from
            ///the beginning of it, and after_length from its end (see done event
            ///sequence).
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset to initial on the next zwp_text_input_v3.done event.
            ///
            ///The initial values of both before_length and after_length are 0.
            ///</summary>
 
            protected virtual void DeleteSurroundingText(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @beforeLength, uint @afterLength)
            {
            }

            ///<summary>
            ///Instruct the application to apply changes to state requested by the
            ///preedit_string, commit_string delete_surrounding_text, and action
            ///events.
            ///
            ///The state relating to these events is double-buffered, and each one
            ///modifies the pending state. This event replaces the current state with
            ///the pending state.
            ///
            ///The application must proceed by evaluating the changes in the following
            ///order:
            ///
            ///1. Replace existing preedit string with the cursor.
            ///2. Delete requested surrounding text.
            ///3. Insert commit string with the cursor at its end.
            ///4. Calculate surrounding text to send.
            ///5. Insert new preedit text in cursor position.
            ///6. Place cursor inside preedit text.
            ///7. Perform the requested action.
            ///
            ///The serial number reflects the last state of the zwp_text_input_v3
            ///object known to the compositor. The value of the serial argument must
            ///be equal to the number of commit requests already issued on that object.
            ///
            ///When the client receives a done event with a serial different than the
            ///number of past commit requests, it must proceed with evaluating and
            ///applying the changes as normal, except it should not change the current
            ///state of the zwp_text_input_v3 object. All pending state requests
            ///(set_surrounding_text, set_content_type and set_cursor_rectangle) on
            ///the zwp_text_input_v3 object should be sent and committed after
            ///receiving a zwp_text_input_v3.done event with a matching serial.
            ///</summary>
 
            protected virtual void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @serial)
            {
            }

            ///<summary>
            ///An action was performed on this text input.
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset to initial on the next zwp_text_input_v3.done event.
            ///
            ///The initial value of action is none.
            ///</summary>
 
            protected virtual void Action(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, ActionEnum @action, uint @serial)
            {
            }

            ///<summary>
            ///Notify the application of language used by the input method.
            ///
            ///This event will be sent on creation if known and for all subsequent changes.
            ///
            ///The language should be specified as an IETF BCP 47 tag.
            ///Setting an empty string will reset any known language back to the default unknown state.
            ///</summary>
 
            protected virtual void Language(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string @language)
            {
            }

            ///<summary>
            ///Notify of contextual hints for the pre-edit string. This
            ///event is always sent together with a zwp_text_input_v3.preedit_string
            ///event.
            ///
            ///The parameters start and end are counted in bytes relative to the
            ///beginning of the text buffer submitted through
            ///zwp_text_input_v3.preedit_string, and represent the substring in the
            ///pre-edit text affected by the hint.
            ///
            ///Multiple events may be submitted if the preedit string has different
            ///sections. The extent of hints may overlap. The parts of the preedit
            ///string that are not covered by any zwp_text_input_v3.preedit_hint event,
            ///the text will be considered unhinted. This is also the case if no
            ///preedit_hint event is sent.
            ///
            ///Clients should provide recognizable visuals to these hints. if they are
            ///unable to comply with this requisition, it may be preferable for them
            ///keep the preedit_shown content hint disabled.
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset on the next zwp_text_input_v3.done event.
            ///</summary>
 
            protected virtual void PreeditHint(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @start, uint @end, PreeditHintEnum @hint)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Enter(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetProxy<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface>(0));
                        break;
                    case 1:
                        this.Leave(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetProxy<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface>(0));
                        break;
                    case 2:
                        this.PreeditString(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetString(0), 
                        arguments.GetInt32(1), 
                        arguments.GetInt32(2));
                        break;
                    case 3:
                        this.CommitString(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetString(0));
                        break;
                    case 4:
                        this.DeleteSurroundingText(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetUInt32(0), 
                        arguments.GetUInt32(1));
                        break;
                    case 5:
                        this.Done(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetUInt32(0));
                        break;
                    case 6:
                        this.Action(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, (ActionEnum)
                        arguments.GetUInt32(0), 
                        arguments.GetUInt32(1));
                        break;
                    case 7:
                        this.Language(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetString(0)!);
                        break;
                    case 8:
                        this.PreeditHint(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)arguments.Sender, 
                        arguments.GetUInt32(0), 
                        arguments.GetUInt32(1), (PreeditHintEnum)
                        arguments.GetUInt32(2));
                        break;
                }
            }

            ///<summary>
            ///Notify of contextual hints for the pre-edit string. This
            ///event is always sent together with a zwp_text_input_v3.preedit_string
            ///event.
            ///
            ///The parameters start and end are counted in bytes relative to the
            ///beginning of the text buffer submitted through
            ///zwp_text_input_v3.preedit_string, and represent the substring in the
            ///pre-edit text affected by the hint.
            ///
            ///Multiple events may be submitted if the preedit string has different
            ///sections. The extent of hints may overlap. The parts of the preedit
            ///string that are not covered by any zwp_text_input_v3.preedit_hint event,
            ///the text will be considered unhinted. This is also the case if no
            ///preedit_hint event is sent.
            ///
            ///Clients should provide recognizable visuals to these hints. if they are
            ///unable to comply with this requisition, it may be preferable for them
            ///keep the preedit_shown content hint disabled.
            ///
            ///Values set with this event are double-buffered. They must be applied
            ///and reset on the next zwp_text_input_v3.done event.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void EnterDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface);
                public EnterDelegate? OnEnter { get; init; }

                protected override void Enter(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface) => OnEnter?.Invoke(eventSender, @surface);
                public delegate void LeaveDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface);
                public LeaveDelegate? OnLeave { get; init; }

                protected override void Leave(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface? @surface) => OnLeave?.Invoke(eventSender, @surface);
                public delegate void PreeditStringDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text, int @cursorBegin, int @cursorEnd);
                public PreeditStringDelegate? OnPreeditString { get; init; }

                protected override void PreeditString(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text, int @cursorBegin, int @cursorEnd) => OnPreeditString?.Invoke(eventSender, @text, @cursorBegin, @cursorEnd);
                public delegate void CommitStringDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text);
                public CommitStringDelegate? OnCommitString { get; init; }

                protected override void CommitString(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string? @text) => OnCommitString?.Invoke(eventSender, @text);
                public delegate void DeleteSurroundingTextDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @beforeLength, uint @afterLength);
                public DeleteSurroundingTextDelegate? OnDeleteSurroundingText { get; init; }

                protected override void DeleteSurroundingText(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @beforeLength, uint @afterLength) => OnDeleteSurroundingText?.Invoke(eventSender, @beforeLength, @afterLength);
                public delegate void DoneDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @serial);
                public DoneDelegate? OnDone { get; init; }

                protected override void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @serial) => OnDone?.Invoke(eventSender, @serial);
                public delegate void ActionDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, ActionEnum @action, uint @serial);
                public ActionDelegate? OnAction { get; init; }

                protected override void Action(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, ActionEnum @action, uint @serial) => OnAction?.Invoke(eventSender, @action, @serial);
                public delegate void LanguageDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string @language);
                public LanguageDelegate? OnLanguage { get; init; }

                protected override void Language(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, string @language) => OnLanguage?.Invoke(eventSender, @language);
                public delegate void PreeditHintDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @start, uint @end, PreeditHintEnum @hint);
                public PreeditHintDelegate? OnPreeditHint { get; init; }

                protected override void PreeditHint(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 eventSender, uint @start, uint @end, PreeditHintEnum @hint) => OnPreeditHint?.Invoke(eventSender, @start, @end, @hint);
            }
        }

        ///<summary>
        ///Reason for the change of surrounding text or cursor posision.
        ///</summary>
 
        public enum ChangeCauseEnum
        {
            ///<summary>input method caused the change</summary>
 
            InputMethod = 0,
            ///<summary>something else than the input method caused the change</summary>
 
            Other = 1
        }

        ///<summary>
        ///Content hint is a bitmask to allow to modify the behavior of the text
        ///input.
        ///</summary>
 
        [Flags]
        public enum ContentHintEnum
        {
            ///<summary>no special behavior</summary>
 
            None = 0x0,
            ///<summary>suggest word completions</summary>
 
            Completion = 0x1,
            ///<summary>suggest word corrections</summary>
 
            Spellcheck = 0x2,
            ///<summary>switch to uppercase letters at the start of a sentence</summary>
 
            AutoCapitalization = 0x4,
            ///<summary>prefer lowercase letters</summary>
 
            Lowercase = 0x8,
            ///<summary>prefer uppercase letters</summary>
 
            Uppercase = 0x10,
            ///<summary>prefer casing for titles and headings (can be language dependent)</summary>
 
            Titlecase = 0x20,
            ///<summary>characters should be hidden</summary>
 
            HiddenText = 0x40,
            ///<summary>typed text should not be stored</summary>
 
            SensitiveData = 0x80,
            ///<summary>just Latin characters should be entered</summary>
 
            Latin = 0x100,
            ///<summary>the text input is multiline</summary>
 
            Multiline = 0x200,
            ///<summary>an on-screen way to fill in the input is already provided by the client</summary>
 
            OnScreenInputProvided = 0x400,
            ///<summary>prefer not offering emoji support</summary>
 
            NoEmoji = 0x800,
            ///<summary>the text input will display preedit text in place</summary>
 
            PreeditShown = 0x1000
        }

        ///<summary>
        ///The content purpose allows to specify the primary purpose of a text
        ///input.
        ///
        ///This allows an input method to show special purpose input panels with
        ///extra characters or to disallow some characters.
        ///</summary>
 
        public enum ContentPurposeEnum
        {
            ///<summary>default input, allowing all characters</summary>
 
            Normal = 0,
            ///<summary>allow only alphabetic characters</summary>
 
            Alpha = 1,
            ///<summary>allow only digits</summary>
 
            Digits = 2,
            ///<summary>input a number (including decimal separator and sign)</summary>
 
            Number = 3,
            ///<summary>input a phone number</summary>
 
            Phone = 4,
            ///<summary>input an URL</summary>
 
            Url = 5,
            ///<summary>input an email address</summary>
 
            Email = 6,
            ///<summary>input a name of a person</summary>
 
            Name = 7,
            ///<summary>input a password (combine with sensitive_data hint)</summary>
 
            Password = 8,
            ///<summary>input is a numeric password (combine with sensitive_data hint)</summary>
 
            Pin = 9,
            ///<summary>input a date</summary>
 
            Date = 10,
            ///<summary>input a time</summary>
 
            Time = 11,
            ///<summary>input a date and time</summary>
 
            Datetime = 12,
            ///<summary>input for a terminal</summary>
 
            Terminal = 13
        }

        public enum ErrorEnum
        {
            ///<summary>an invalid or duplicate action was specified</summary>
 
            InvalidAction = 0
        }

        ///<summary>
        ///A possible action to perform on a text input.
        ///
        ///The submit action is intended for input entries that expect some sort of
        ///activation after user interaction, e.g. the URL entry in a browser.
        ///</summary>
 
        public enum ActionEnum
        {
            ///<summary>no action</summary>
 
            None = 0,
            ///<summary>the action is submitted</summary>
 
            Submit = 1
        }

        ///<summary>
        ///Style hints for the preedit string.
        ///</summary>
 
        public enum PreeditHintEnum
        {
            ///<summary>simple pre-edit text style, typically underlined</summary>
 
            Whole = 1,
            ///<summary>hint for a selected piece of text, e.g. per-character navigation and composition</summary>
 
            Selection = 2,
            ///<summary>predicted text, not typed by the user</summary>
 
            Prediction = 3,
            ///<summary>prefixed text not being currently edited, e.g. prior to a 'selection' section</summary>
 
            Prefix = 4,
            ///<summary>suffixed text not being currently edited, e.g. after a 'selection' section</summary>
 
            Suffix = 5,
            ///<summary>spelling error</summary>
 
            SpellingError = 6,
            ///<summary>wrong composition, e.g. user input that can not be transliterated</summary>
 
            ComposeError = 7
        }

        private ZwpTextInputV3(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpTextInputV3 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpTextInputV3)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///A factory for text-input objects. This object is a global singleton.
    ///</summary>
 
    public sealed unsafe partial class ZwpTextInputManagerV3 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_text_input_manager_v3", 2) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_text_input") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat.ProxyType)) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpTextInputManagerV3), (ctx) => new ZwpTextInputManagerV3(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputManagerV3 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputManagerV3.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputManagerV3>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the wp_text_input_manager object.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Creates a new text-input object for a given seat.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3 GetTextInput(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat @seat, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@seat);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.TextInputUnstableV3.ZwpTextInputV3>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private ZwpTextInputManagerV3(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpTextInputManagerV3 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpTextInputManagerV3)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}