// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1
{
    ///<summary>
    ///A global interface for requesting surfaces to use fractional scales.
    ///</summary>
 
    public sealed unsafe partial class WpFractionalScaleManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_fractional_scale_manager_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_fractional_scale") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddError(0U, "fractional_scale_exists", "the surface already has a fractional_scale object associated") 
        .Build() 
        , typeof(WpFractionalScaleManagerV1), (ctx) => new WpFractionalScaleManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Informs the server that the client will not be using this protocol
        ///object anymore. This does not affect any other objects,
        ///wp_fractional_scale_v1 objects included.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Create an add-on object for the the wl_surface to let the compositor
        ///request fractional scales. If the given wl_surface already has a
        ///wp_fractional_scale_v1 object associated, the fractional_scale_exists
        ///protocol error is raised.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1 GetFractionalScale(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@surface);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        public enum ErrorEnum
        {
            ///<summary>the surface already has a fractional_scale object associated</summary>
 
            FractionalScaleExists = 0
        }

        private WpFractionalScaleManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpFractionalScaleManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpFractionalScaleManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///An additional interface to a wl_surface object which allows the compositor
    ///to inform the client of the preferred scale.
    ///</summary>
 
    public sealed unsafe partial class WpFractionalScaleV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("wp_fractional_scale_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("preferred_scale") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Build() 
        ) 
        .Build() 
        , typeof(WpFractionalScaleV1), (ctx) => new WpFractionalScaleV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Destroy the fractional scale object. When this object is destroyed,
        ///preferred_scale events will no longer be sent.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Notification of a new preferred scale for this surface that the
            ///compositor suggests that the client should use.
            ///
            ///The sent scale is the numerator of a fraction with a denominator of 120.
            ///</summary>
 
            protected virtual void PreferredScale(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1 eventSender, uint @scale)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.PreferredScale(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1)arguments.Sender, 
                        arguments.GetUInt32(0));
                        break;
                }
            }

            ///<summary>
            ///Notification of a new preferred scale for this surface that the
            ///compositor suggests that the client should use.
            ///
            ///The sent scale is the numerator of a fraction with a denominator of 120.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void PreferredScaleDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1 eventSender, uint @scale);
                public PreferredScaleDelegate? OnPreferredScale { get; init; }

                protected override void PreferredScale(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.FractionalScaleV1.WpFractionalScaleV1 eventSender, uint @scale) => OnPreferredScale?.Invoke(eventSender, @scale);
            }
        }

        private WpFractionalScaleV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static WpFractionalScaleV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (WpFractionalScaleV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}