// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1
{
    ///<summary>
    ///A global interface used for informing the compositor about applications
    ///being activated or started, or for applications to request to be
    ///activated.
    ///</summary>
 
    public sealed unsafe partial class XdgActivationV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("xdg_activation_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_activation_token") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("activate") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .Build() 
        , typeof(XdgActivationV1), (ctx) => new XdgActivationV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Notify the compositor that the xdg_activation object will no longer be
        ///used.
        ///
        ///The child objects created via this interface are unaffected and should
        ///be destroyed separately.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Creates an xdg_activation_token_v1 object that will provide
        ///the initiating client with a unique token for this activation. This
        ///token should be offered to the clients to be activated.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1 GetActivationToken(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1>(eventsListener, dispatchOnQueue);
            }
        }

        ///<summary>
        ///Requests surface activation. It's up to the compositor to display
        ///this information as desired, for example by placing the surface above
        ///the rest.
        ///
        ///The compositor may know who requested this by checking the activation
        ///token and might decide not to follow through with the activation if it's
        ///considered unwanted.
        ///
        ///Compositors can ignore unknown activation tokens when an invalid
        ///token is passed.
        ///</summary>
 
        public void Activate(string @token, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@token);
                __call.Arg(@surface);
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private XdgActivationV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static XdgActivationV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (XdgActivationV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///An object for setting up a token and receiving a token handle that can
    ///be passed as an activation token to another client.
    ///
    ///The object is created using the xdg_activation_v1.get_activation_token
    ///request. This object should then be populated with the app_id, surface
    ///and serial information and committed. The compositor shall then issue a
    ///done event with the token. In case the request's parameters are invalid,
    ///the compositor will provide an invalid token.
    ///</summary>
 
    public sealed unsafe partial class XdgActivationTokenV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("xdg_activation_token_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_serial") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_app_id") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("set_surface") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface.ProxyType)) 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("commit") 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("done") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.String) 
        .Build() 
        ) 
        .AddError(0U, "already_used", "The token has already been used previously") 
        .Build() 
        , typeof(XdgActivationTokenV1), (ctx) => new XdgActivationTokenV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Provides information about the seat and serial event that requested the
        ///token.
        ///
        ///The serial can come from an input or focus event. For instance, if a
        ///click triggers the launch of a third-party client, the launcher client
        ///should send a set_serial request with the serial and seat from the
        ///wl_pointer.button event.
        ///
        ///Some compositors might refuse to activate toplevels when the token
        ///doesn't have a valid and recent enough event serial.
        ///
        ///Must be sent before commit. This information is optional.
        ///</summary>
 
        public void SetSerial(uint @serial, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSeat @seat)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Arg(@serial);
                __call.Arg(@seat);
                __call.Invoke();
            }
        }

        ///<summary>
        ///The requesting client can specify an app_id to associate the token
        ///being created with it.
        ///
        ///Must be sent before commit. This information is optional.
        ///</summary>
 
        public void SetAppId(string @appId)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.Arg(@appId);
                __call.Invoke();
            }
        }

        ///<summary>
        ///This request sets the surface requesting the activation. Note, this is
        ///different from the surface that will be activated.
        ///
        ///Some compositors might refuse to activate toplevels when the token
        ///doesn't have a requesting surface.
        ///
        ///Must be sent before commit. This information is optional.
        ///</summary>
 
        public void SetSurface(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlSurface @surface)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 2))
            {
                __call.Arg(@surface);
                __call.Invoke();
            }
        }

        ///<summary>
        ///Requests an activation token based on the different parameters that
        ///have been offered through set_serial, set_surface and set_app_id.
        ///</summary>
 
        public void Commit()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 3))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Notify the compositor that the xdg_activation_token_v1 object will no
        ///longer be used. The received token stays valid.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 4))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///The 'done' event contains the unique token of this activation request
            ///and notifies that the provider is done.
            ///</summary>
 
            protected virtual void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1 eventSender, string @token)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.Done(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1)arguments.Sender, 
                        arguments.GetString(0)!);
                        break;
                }
            }

            ///<summary>
            ///The 'done' event contains the unique token of this activation request
            ///and notifies that the provider is done.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void DoneDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1 eventSender, string @token);
                public DoneDelegate? OnDone { get; init; }

                protected override void Done(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.XdgActivationV1.XdgActivationTokenV1 eventSender, string @token) => OnDone?.Invoke(eventSender, @token);
            }
        }

        public enum ErrorEnum
        {
            ///<summary>The token has already been used previously</summary>
 
            AlreadyUsed = 0
        }

        private XdgActivationTokenV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static XdgActivationTokenV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (XdgActivationTokenV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}