// <auto-generated/>
// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the
// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML
// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run
// the generator instead (see tools/WaylandBindingsGenerator/README.md).
#pragma warning disable
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop;
using CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland;

#nullable enable
namespace CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1
{
    ///<summary>
    ///A global interface used for getting the relative pointer object for a
    ///given pointer.
    ///</summary>
 
    public sealed unsafe partial class ZwpRelativePointerManagerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_relative_pointer_manager_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("get_relative_pointer") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.NewId(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1.ProxyType)) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Object(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer.ProxyType)) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpRelativePointerManagerV1), (ctx) => new ZwpRelativePointerManagerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerManagerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerManagerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerManagerV1>(name, version, eventsListener, dispatchOnQueue);
        ///<summary>
        ///Used by the client to notify the server that it will no longer use this
        ///relative pointer manager object.
        ///</summary>
 
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        ///<summary>
        ///Create a relative pointer interface given a wl_pointer object. See the
        ///wp_relative_pointer interface for more details.
        ///</summary>
 
        public CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1 GetRelativePointer(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlPointer @pointer, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null)
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 1))
            {
                __call.ArgNewId();
                __call.Arg(@pointer);
                return (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1)__call.InvokeNewId<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1>(eventsListener, dispatchOnQueue);
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
            }

            public sealed class Relay : Listener
            {
            }
        }

        private ZwpRelativePointerManagerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpRelativePointerManagerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpRelativePointerManagerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }

    ///<summary>
    ///A wp_relative_pointer object is an extension to the wl_pointer interface
    ///used for emitting relative pointer events. It shares the same focus as
    ///wl_pointer objects of the same seat and will only emit events when it has
    ///focus.
    ///</summary>
 
    public sealed unsafe partial class ZwpRelativePointerV1 : WlProxy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider
    {
        public static global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor ProxyType { get; } = new global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyTypeDescriptor(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlInterfaceDescription.Create("zwp_relative_pointer_v1", 1) 
        .AddMethod(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("destroy") 
        .IsDestructor() 
        .Build() 
        ) 
        .AddEvent(
        global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageDescription.Create("relative_motion") 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.UInt32) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Add(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlMessageArgumentDescription.Fixed) 
        .Build() 
        ) 
        .Build() 
        , typeof(ZwpRelativePointerV1), (ctx) => new ZwpRelativePointerV1(ctx), false);
        
        public static CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1 Bind(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland.WlRegistry registry, uint name, uint version, CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1.Listener? eventsListener = null, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlTargetQueue? dispatchOnQueue = null) => 
        registry.Bind<CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1>(name, version, eventsListener, dispatchOnQueue);
        public void Destroy()
        {
            using (var __call = global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WaylandCallBuilder.Create(this, 0))
            {
                __call.Invoke();
            }
        }

        public abstract class Listener : global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener
        {
            ///<summary>
            ///Relative x/y pointer motion from the pointer of the seat associated with
            ///this object.
            ///
            ///A relative motion is in the same dimension as regular wl_pointer motion
            ///events, except they do not represent an absolute position. For example,
            ///moving a pointer from (x, y) to (x', y') would have the equivalent
            ///relative motion (x' - x, y' - y). If a pointer motion caused the
            ///absolute pointer position to be clipped by for example the edge of the
            ///monitor, the relative motion is unaffected by the clipping and will
            ///represent the unclipped motion.
            ///
            ///This event also contains non-accelerated motion deltas. The
            ///non-accelerated delta is, when applicable, the regular pointer motion
            ///delta as it was before having applied motion acceleration and other
            ///transformations such as normalization.
            ///
            ///Note that the non-accelerated delta does not represent 'raw' events as
            ///they were read from some device. Pointer motion acceleration is device-
            ///and configuration-specific and non-accelerated deltas and accelerated
            ///deltas may have the same value on some devices.
            ///
            ///Relative motions are not coupled to wl_pointer.motion events, and can be
            ///sent in combination with such events, but also independently. There may
            ///also be scenarios where wl_pointer.motion is sent, but there is no
            ///relative motion. The order of an absolute and relative motion event
            ///originating from the same physical motion is not guaranteed.
            ///
            ///If the client needs button events or focus state, it can receive them
            ///from a wl_pointer object of the same seat that the wp_relative_pointer
            ///object is associated with.
            ///</summary>
 
            protected virtual void RelativeMotion(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1 eventSender, uint @utimeHi, uint @utimeLo, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dx, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dxUnaccel, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dyUnaccel)
            {
            }

            void global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlEventsListener.DispatchEvent(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlEventArgs arguments)
            {
                switch (arguments.Opcode)
                {
                    case 0:
                        this.RelativeMotion(
                        (CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1)arguments.Sender, 
                        arguments.GetUInt32(0), 
                        arguments.GetUInt32(1), 
                        arguments.GetWlFixed(2), 
                        arguments.GetWlFixed(3), 
                        arguments.GetWlFixed(4), 
                        arguments.GetWlFixed(5));
                        break;
                }
            }

            ///<summary>
            ///Relative x/y pointer motion from the pointer of the seat associated with
            ///this object.
            ///
            ///A relative motion is in the same dimension as regular wl_pointer motion
            ///events, except they do not represent an absolute position. For example,
            ///moving a pointer from (x, y) to (x', y') would have the equivalent
            ///relative motion (x' - x, y' - y). If a pointer motion caused the
            ///absolute pointer position to be clipped by for example the edge of the
            ///monitor, the relative motion is unaffected by the clipping and will
            ///represent the unclipped motion.
            ///
            ///This event also contains non-accelerated motion deltas. The
            ///non-accelerated delta is, when applicable, the regular pointer motion
            ///delta as it was before having applied motion acceleration and other
            ///transformations such as normalization.
            ///
            ///Note that the non-accelerated delta does not represent 'raw' events as
            ///they were read from some device. Pointer motion acceleration is device-
            ///and configuration-specific and non-accelerated deltas and accelerated
            ///deltas may have the same value on some devices.
            ///
            ///Relative motions are not coupled to wl_pointer.motion events, and can be
            ///sent in combination with such events, but also independently. There may
            ///also be scenarios where wl_pointer.motion is sent, but there is no
            ///relative motion. The order of an absolute and relative motion event
            ///originating from the same physical motion is not guaranteed.
            ///
            ///If the client needs button events or focus state, it can receive them
            ///from a wl_pointer object of the same seat that the wp_relative_pointer
            ///object is associated with.
            ///</summary>
 
            public sealed class Relay : Listener
            {
                public delegate void RelativeMotionDelegate(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1 eventSender, uint @utimeHi, uint @utimeLo, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dx, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dxUnaccel, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dyUnaccel);
                public RelativeMotionDelegate? OnRelativeMotion { get; init; }

                protected override void RelativeMotion(CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.RelativePointerUnstableV1.ZwpRelativePointerV1 eventSender, uint @utimeHi, uint @utimeLo, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dx, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dy, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dxUnaccel, global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlFixed @dyUnaccel) => OnRelativeMotion?.Invoke(eventSender, @utimeHi, @utimeLo, @dx, @dy, @dxUnaccel, @dyUnaccel);
            }
        }

        private ZwpRelativePointerV1(global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext context) : base(context)
        {
        }

        public static ZwpRelativePointerV1 Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
        {
            return (ZwpRelativePointerV1)WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
        }
    }
}