using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyMetadata("IsTrimmable", "True")]

[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RuntimeTests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RuntimeTests.Windows")]
[assembly: InternalsVisibleTo("SamplesApp")]
[assembly: InternalsVisibleTo("SamplesApp.Droid")]
[assembly: InternalsVisibleTo("SamplesApp.macOS")]
[assembly: InternalsVisibleTo("SamplesApp.Wasm")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.App.Mcp.Client")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit.Tests")]
// The host-free engine proof (WPE1 C12): drives Engine/TriPaneLayoutState with no XAML.
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Engine.Tests")]

// CodeBrix.Platform.UI.Toolkit.Core (the platform-neutral Core assembly this file is compiled into since the Core/Skia split):
// its Skia twin, which implements the platform contracts and reaches Core internals,
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit")]
// and, by rule (decision P4), the CodeBrix.Android and CodeBrix.Mobile assemblies (and their tests) for the same library.
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit.Tests")]

// Element handler seam (WPH1, decisions D-P3 and the AP1-B cross-assembly rule): the CodeBrix.Android and CodeBrix.Mobile
// counterparts (and their tests) of every Skia-side assembly granted above - the framework Skia twins and the add-ins'
// platform assemblies - so that a platform implementation of a Core contract, or a platform handler, compiles against the
// same internals the Skia side uses. This Core assembly also grants every add-in's Android and Mobile name (D-P3).
[assembly: InternalsVisibleTo("CodeBrix.Android.AppSettings")]
[assembly: InternalsVisibleTo("CodeBrix.Android.AppSettings.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.AppSettings")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.AppSettings.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.SkiaSharp.Views")]
[assembly: InternalsVisibleTo("CodeBrix.Android.SkiaSharp.Views.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.SkiaSharp.Views")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.SkiaSharp.Views.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AdvancedTextEdit")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AdvancedTextEdit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AdvancedTextEdit")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AdvancedTextEdit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AudioPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AudioPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AudioPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AudioPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.CommandBar")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.CommandBar.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.CommandBar")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.CommandBar.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.FlexPanel")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.FlexPanel.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.FlexPanel")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.FlexPanel.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.MediaPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.MediaPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.MediaPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.MediaPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.PlotterView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.PlotterView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.PlotterView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.PlotterView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TerminalView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TerminalView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TerminalView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TerminalView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TextLayout")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TextLayout.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TextLayout")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TextLayout.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.VideoPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.VideoPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.VideoPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.VideoPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.WebView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.WebView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.WebView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.WebView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics2DSK")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics2DSK.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics2DSK")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics2DSK.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics3DGL")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics3DGL.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics3DGL")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics3DGL.Tests")]
