using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Windows.Foundation.Collections;

namespace Microsoft.UI.Xaml.Controls;

/// <summary>
/// Group headers of a grouped ItemsControl: an items source that is a grouped collection view
/// (CollectionViewSource.IsSourceGrouped) plus a <see cref="GroupStyle"/>.
/// </summary>
/// <remarks>
/// Two paths, as in WinUI: a virtualizing panel (ItemsStackPanel's managed layout) realizes a header container per group
/// (ListViewHeaderItem / GridViewHeaderItem, see <see cref="GetGroupHeaderContainer"/>) between the item containers; any
/// other panel receives one <see cref="GroupItem"/> per group, which shows the header and the group's item containers.
/// Nothing here runs unless <see cref="ShowsGroupHeaders"/> is true, so an ungrouped control is laid out exactly as before.
/// </remarks>
public partial class ItemsControl
{
	/// <summary>
	/// Set on a group header container (and on a <see cref="GroupItem"/>) to the display index of the group it shows; -1
	/// (the default) on every other element. Item containers never carry it.
	/// </summary>
	internal static DependencyProperty GroupHeaderIndexForContainerProperty { get; } =
		DependencyProperty.RegisterAttached(
			"GroupHeaderIndexForContainer",
			typeof(int),
			typeof(ItemsControl),
			new FrameworkPropertyMetadata(-1));

	/// <summary>True while the items panel holds <see cref="GroupItem"/>s this control generated.</summary>
	private bool _groupItemsRealized;

	/// <summary>The GroupStyles whose PropertyChanged this control listens to.</summary>
	private readonly List<GroupStyle> _observedGroupStyles = new List<GroupStyle>();

	/// <summary>
	/// Gets whether this control shows group headers: its items source is grouped (<see cref="IsGrouping"/>) AND it has a
	/// <see cref="GroupStyle"/>. A grouped source without a GroupStyle shows its items without headers, as in WinUI.
	/// </summary>
	internal bool ShowsGroupHeaders => IsGrouping && GroupStyle.Count > 0;

	/// <summary>Gets whether the element is a group header container (or a GroupItem) generated by an ItemsControl.</summary>
	/// <param name="element">The element.</param>
	/// <returns>True for a group header container.</returns>
	internal static bool IsGroupHeaderContainer(DependencyObject element)
		=> element is not null && (int)element.GetValue(GroupHeaderIndexForContainerProperty) >= 0;

	/// <summary>
	/// Creates the header container for the group at <paramref name="displayGroupIndex"/> and prepares it (see
	/// <see cref="PrepareGroupHeaderContainer"/>).
	/// </summary>
	/// <param name="displayGroupIndex">The display index of the group.</param>
	/// <returns>The prepared header container.</returns>
	internal ContentControl CreateGroupHeaderContainer(int displayGroupIndex)
	{
		var header = GetGroupHeaderContainer(GetGroupAtDisplaySection(displayGroupIndex)?.Group);
		PrepareGroupHeaderContainer(header, displayGroupIndex);
		return header;
	}

	/// <summary>
	/// Prepares a group header container for the group at <paramref name="displayGroupIndex"/>: its Content and
	/// DataContext are the group (ICollectionViewGroup.Group), its ContentTemplate / ContentTemplateSelector come from
	/// GroupStyle.HeaderTemplate / HeaderTemplateSelector and its Style from GroupStyle.HeaderContainerStyle (otherwise the
	/// container's default style).
	/// </summary>
	/// <param name="header">The header container.</param>
	/// <param name="displayGroupIndex">The display index of the group.</param>
	internal void PrepareGroupHeaderContainer(ContentControl header, int displayGroupIndex)
	{
		var group = GetGroupAtDisplaySection(displayGroupIndex);
		var groupStyle = GetGroupStyle();

		header.SetValue(GroupHeaderIndexForContainerProperty, displayGroupIndex);

		if (groupStyle?.HeaderContainerStyle is { } containerStyle)
		{
			header.Style = containerStyle;
			header.IsStyleSetFromItemsControl = true;
		}
		else if (header.IsStyleSetFromItemsControl)
		{
			header.ClearValue(FrameworkElement.StyleProperty);
			header.IsStyleSetFromItemsControl = false;
		}

		header.ContentTemplate = groupStyle?.HeaderTemplate;
		header.ContentTemplateSelector = groupStyle?.HeaderTemplateSelector;
		header.DataContext = group?.Group;
		header.Content = group?.Group;
	}

	/// <summary>Clears a group header container that no longer shows a group.</summary>
	/// <param name="header">The header container.</param>
	internal void ClearGroupHeaderContainer(ContentControl header)
	{
		header.ClearValue(GroupHeaderIndexForContainerProperty);
		header.ClearValue(ContentControl.ContentProperty);
		header.ClearValue(FrameworkElement.DataContextProperty);
	}

	/// <summary>Gets the header container the control realized for a display group, or null when none is realized.</summary>
	/// <param name="displayGroupIndex">The display index of the group.</param>
	/// <returns>The realized header container (a GroupItem of a plain ItemsControl), or null.</returns>
	internal ContentControl GetRealizedGroupHeader(int displayGroupIndex)
	{
		if (_groupItemsRealized && ItemsPanelRoot is { } panel)
		{
			foreach (var child in panel.Children)
			{
				if (child is GroupItem groupItem && groupItem.GroupIndex == displayGroupIndex)
				{
					return groupItem.HeaderContainer ?? groupItem;
				}
			}
		}

		return null;
	}

	// ------------------------------------------------------------------ GroupItem path (non-virtualizing panels)

	/// <summary>
	/// Gets whether the items panel receives <see cref="GroupItem"/>s: the control shows group headers and manages the
	/// children of an items panel that is not a virtualizing panel (WinUI's non-modern panel grouping).
	/// </summary>
	private bool UsesGroupItems
		=> ShowsGroupHeaders
			&& ItemsPanelRoot is not null
			&& ItemsPanelRoot is not IVirtualizingPanel
			&& ShouldItemsControlManageChildren;

	/// <summary>
	/// Regenerates the GroupItems of the items panel: one per display group, each with its header and a panel holding the
	/// containers of the group's items (created and prepared by the normal container path, with their FLAT indexes).
	/// </summary>
	private void UpdateGroupItems()
	{
		DismantleGroupItems();

		var panel = ItemsPanelRoot;

		// Containers left from an ungrouped state (the panel held item containers directly).
		foreach (var child in panel.Children.ToArray())
		{
			CleanUpContainer(child);
			child.ClearValue(IndexForItemContainerProperty);
		}

		panel.Children.Clear();

		var flatIndex = 0;
		var groupCount = NumberOfDisplayGroups;
		for (var displayGroupIndex = 0; displayGroupIndex < groupCount; displayGroupIndex++)
		{
			var group = GetGroupAtDisplaySection(displayGroupIndex);
			var groupItem = new GroupItem();
			PrepareGroupItem(groupItem, displayGroupIndex, group);

			var itemsPanel = groupItem.ItemsPanel;
			var count = group?.GroupItems?.Count ?? 0;
			for (var row = 0; row < count; row++)
			{
				var container = CreateContainerForItemsHost(flatIndex++);
				if (container is UIElement element)
				{
					itemsPanel.Children.Add(element);
				}
			}

			panel.Children.Add(groupItem);
		}

		_groupItemsRealized = true;
	}

	/// <summary>Gives a GroupItem its group: header, style, and the panel of its items.</summary>
	private void PrepareGroupItem(GroupItem groupItem, int displayGroupIndex, ICollectionViewGroup group)
	{
		var groupStyle = GetGroupStyle();

		groupItem.GroupIndex = displayGroupIndex;
		groupItem.SetValue(GroupHeaderIndexForContainerProperty, displayGroupIndex);
		groupItem.DataContext = group?.Group;

		var containerStyle = groupStyle?.ContainerStyle ?? groupStyle?.ContainerStyleSelector?.SelectStyle(group, groupItem);
		if (containerStyle is not null)
		{
			groupItem.Style = containerStyle;
		}

		if (this is ListViewBase)
		{
			// A ListView / GridView heads each group with its own header container (ListViewHeaderItem /
			// GridViewHeaderItem), the element WinUI's modern panels realize for a group.
			var header = CreateGroupHeaderContainer(displayGroupIndex);
			groupItem.HeaderContainer = header;
			groupItem.Content = header;
		}
		else
		{
			groupItem.ContentTemplate = groupStyle?.HeaderTemplate;
			groupItem.ContentTemplateSelector = groupStyle?.HeaderTemplateSelector;
			groupItem.Content = group?.Group;
		}

		var itemsPanel = (groupStyle?.Panel as IFrameworkTemplateInternal)?.LoadContent(groupItem) as Panel
			?? (this is GridView ? (ItemsPanel as IFrameworkTemplateInternal)?.LoadContent(groupItem) as Panel : null)
			?? new StackPanel();
		itemsPanel.SetItemsOwner(this);
		groupItem.SetItemsPanel(itemsPanel);
	}

	/// <summary>Removes the GroupItems of the items panel, cleaning up the item containers they hold.</summary>
	private void DismantleGroupItems()
	{
		if (!_groupItemsRealized)
		{
			return;
		}

		_groupItemsRealized = false;

		if (ItemsPanelRoot is not { } panel)
		{
			return;
		}

		foreach (var groupItem in panel.Children.OfType<GroupItem>().ToArray())
		{
			foreach (var container in groupItem.GetItemContainers().ToArray())
			{
				CleanUpContainer(container);
				container.ClearValue(IndexForItemContainerProperty);
			}

			groupItem.ItemsPanel?.Children.Clear();
			groupItem.SetItemsPanel(null);

			if (groupItem.HeaderContainer is { } header)
			{
				ClearGroupHeaderContainer(header);
				groupItem.HeaderContainer = null;
			}

			groupItem.Content = null;
			panel.Children.Remove(groupItem);
		}
	}

	/// <summary>The item containers inside the GroupItems of the items panel, in item order.</summary>
	private IEnumerable<DependencyObject> GetGroupItemContainers(Panel panel)
		=> panel.Children.OfType<GroupItem>().SelectMany(groupItem => groupItem.GetItemContainers());

	// ------------------------------------------------------------------ GroupStyle changes

	/// <summary>Listens to the GroupStyle collection (and to each GroupStyle in it) so that a change regroups the control.</summary>
	private void ObserveGroupStyle()
		=> GroupStyle.VectorChanged += OnGroupStyleVectorChanged;

	private void OnGroupStyleVectorChanged(IObservableVector<GroupStyle> sender, IVectorChangedEventArgs args)
	{
		foreach (var observed in _observedGroupStyles)
		{
			observed.PropertyChanged -= OnGroupStylePropertyChanged;
		}

		_observedGroupStyles.Clear();

		foreach (var groupStyle in GroupStyle)
		{
			if (groupStyle is not null)
			{
				groupStyle.PropertyChanged += OnGroupStylePropertyChanged;
				_observedGroupStyles.Add(groupStyle);
			}
		}

		OnGroupStyleChanged();
	}

	private void OnGroupStylePropertyChanged(object sender, PropertyChangedEventArgs args) => OnGroupStyleChanged();

	/// <summary>A GroupStyle was added, removed or changed: a grouped control regroups (an ungrouped one is not touched).</summary>
	private void OnGroupStyleChanged()
	{
		if (!IsGrouping)
		{
			return;
		}

		ObserveCollectionChanged();
		Refresh();
		UpdateItems(null);
	}
}
