<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PlayTestDemoHead>Win32Skia</PlayTestDemoHead>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants>$(DefineConstants);HAS_CODEBRIX_SKIA_WIN32;__CODEBRIX_SKIA_WIN32__</DefineConstants>
  </PropertyGroup>
  <Import Project="../../PlayTestDemo.Head.targets" />
  <ItemGroup>
    <ProjectReference Include="$(PlayTestDemoPlatformSource)Platform.UI.Runtime.Skia.Win32/Platform.UI.Runtime.Skia.Win32.csproj" />
  </ItemGroup>
</Project>
