// <auto-generated>
#pragma warning disable 108 // new keyword hiding
#pragma warning disable 114 // new keyword hiding
namespace Microsoft.UI.Xaml.Media;

// The type-level NotImplemented marker used to come from the generated file; the API sync generator no longer emits it
// once a hand-written part exists, so it is declared here (unchanged).
[global::CodeBrix.Platform.NotImplemented]
public partial class MicaBackdrop : SystemBackdrop
{
	[global::CodeBrix.Platform.NotImplemented("IS_UNIT_TESTS", "__SKIA__", "__NETSTD_REFERENCE__", "__CODEBRIX_CORE__")]
	public MicaBackdrop()
	{
	}
}
