using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace NWayland.Generator
{
    public partial class WaylandProtocolGenerator
    {
        private readonly Dictionary<string, string> _protocolFullNames = new();
        // Locally-defined interfaces that get an assembly-level proxy-map attribute.
        // Excludes internal-visibility protocols (their types aren't referenceable cross-assembly).
        private readonly Dictionary<string, string> _mappingAttributeInterfaces = new();
        private readonly Dictionary<string, string> _protocolNamespaces = new();
        private readonly HashSet<string> _internalProtocols = new();
        private readonly Dictionary<NwgSourceText, WaylandProtocol> _protocols = new();
        private readonly EquatableArray<NwgArrayTypeMapping> _arrayMappings;

        // Header prepended to every generated file. The output is committed to the repo
        // (generate-once-and-commit), so the header always carries provenance and the
        // warning suppression that auto-generated code gets.
        private const string GeneratedFileHeader =
            "// <auto-generated/>\r\n" +
            "// Generated by tools/WaylandBindingsGenerator — a frozen, CodeBrix-owned fork of the\r\n" +
            "// MIT-licensed NWayland bindings generator — from the MIT-licensed Wayland protocol XML\r\n" +
            "// pinned under tools/WaylandBindingsGenerator/protocols/. Do not edit by hand; re-run\r\n" +
            "// the generator instead (see tools/WaylandBindingsGenerator/README.md).\r\n" +
            "#pragma warning disable\r\n";

        // Namespaces the emitted code lives in / imports (the absorbed NWayland client-support
        // types were renamed into the Interop namespace when they were vendored into the head).
        internal const string InteropNs = "CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop";
        internal const string CoreProtocolNs = "CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Protocols.Wayland";

        public WaylandProtocolGenerator(NwgInputModel model)
        {
            _arrayMappings = model.ArrayMappings;
            foreach(var externalMapping in model.ExternalTypeMappings)
            {
                // TODO gracefully handle name conflicts
                _protocolFullNames.Add(externalMapping.Name, externalMapping.FullTypeName);
            }
            foreach (var src in model.Sources)
            {
                var p = WaylandProtocol.ParseXml(src.Source);
                _protocols[src] = p;
                var ns = $"{src.Namespace}.{Pascalize(p.Name)}";

                _protocolNamespaces.Add(p.Name, ns);
                if (src.Internal)
                    _internalProtocols.Add(p.Name);

                foreach (var i in p.Interfaces)
                {
                    var fullName = $"{ProtocolNamespace(p.Name)}.{Pascalize(i.Name)}";
                    if (_protocolFullNames.ContainsKey(i.Name))
                    {

                        throw new NwGeneratorWithFileException(src.Path,
                            $"Can't add {i.Name} from {p.Name}, {i.Name} is already associated to {_protocolFullNames[i.Name]}");
                    }

                    _protocolFullNames.Add(i.Name, fullName);
                    // Internal bindings get no assembly-level mapping attribute — their types
                    // aren't accessible from other assemblies, so the mapping would be unusable.
                    if (!src.Internal)
                        _mappingAttributeInterfaces.Add(i.Name, fullName);
                }
            }
        }
        
        
        public static void GenerateModel(NwgInputModel nwgInputModel, Action<string, string> addSource)
        {
            var gen = new WaylandProtocolGenerator(nwgInputModel);
            var rv = new Dictionary<string, string>();
            foreach (var p in gen._protocols)
            {
                addSource(p.Value.Name, gen.Generate(p.Value));
            }

            var attributes = new StringBuilder();
            foreach (var iface in gen._mappingAttributeInterfaces)
            {
                attributes.AppendLine($"[assembly:global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.Metadata.NWaylandInterfaceToProxyNameMappingAttribute(\"{iface.Key}\", typeof({iface.Value}))]");
            }

            addSource("__generated-proxy-map", GeneratedFileHeader + attributes.ToString());
        }

        private WaylandProtocol? _currentProtocol;

        Exception CreateError(string message, WaylandProtocolInterface iface, WaylandProtocolMessage? msg = null,
            WaylandProtocolArgument? arg = null)
        {
            var m = iface + ":";
            if (msg != null)
            {
                m += msg.Name + ":";
                if (arg != null)
                    m += arg.Name + ":";
            }

            m += " " + message;
            return CreateError(m);
        }
        Exception CreateError(string message)
        {
            if (_currentProtocol == null)
                return new NwGeneratorException(message);
            else
                return new NwGeneratorWithFileException(message,
                    _protocols.First(x => x.Value == _currentProtocol).Key.Path);
        }
        
        string Generate(WaylandProtocol protocol)
        {
            if (_currentProtocol != null)
                throw new InvalidOperationException("Reentrancy");
            _currentProtocol = protocol;
            try
            {
                var unit = CompilationUnit();
                unit = Generate(unit, protocol);

                return GeneratedFileHeader
                       + unit.NormalizeWhitespace("    ").ToFullString().Replace("//CRLF", "");
            }
            finally
            {
                _currentProtocol = null;
            }
            /*
            var cw = new AdhocWorkspace();
            var formatted = Formatter.Format(unit, cw, cw.Options
                .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInObjectInit, true)
                .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInObjectCollectionArrayInitializers, true)
                .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInAnonymousTypes, true)
                .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInMethods, true)
            );

            return formatted.ToFullString();*/
        }

        private CompilationUnitSyntax Generate(CompilationUnitSyntax code, WaylandProtocol protocol)
        {
            code = code.AddUsings(UsingDirective(IdentifierName("System")))
                .AddUsings(UsingDirective(IdentifierName("System.Runtime.CompilerServices")))
                .AddUsings(UsingDirective(IdentifierName("System.Runtime.InteropServices")))
                .AddUsings(UsingDirective(IdentifierName(InteropNs)))
                .AddUsings(UsingDirective(IdentifierName(CoreProtocolNs)));

            var ns = NamespaceDeclaration(ProtocolNamespaceSyntax(protocol.Name))
                .WithLeadingTrivia(
                    TriviaList(
                        Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true))))
                .NormalizeWhitespace();

            // The top-level interface type carries the binding's accessibility. Nested members
            // (Server, Listener, enums, …) stay public but are effectively scoped by this — so
            // an internal interface type makes the whole binding assembly-private in one place.
            var accessibility = _internalProtocols.Contains(protocol.Name)
                ? SyntaxKind.InternalKeyword
                : SyntaxKind.PublicKeyword;

            foreach (var @interface in protocol.Interfaces)
            {
                var cl = ClassDeclaration(Pascalize(@interface.Name))
                    .WithModifiers(new SyntaxTokenList(
                        Token(accessibility),
                        Token(SyntaxKind.SealedKeyword),
                        Token(SyntaxKind.UnsafeKeyword),
                        Token(SyntaxKind.PartialKeyword)))
                    .AddBaseListTypes(
                        SimpleBaseType(ParseTypeName("WlProxy")),
                        SimpleBaseType(ParseTypeName("global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.IWlProxyTypeDescriptorProvider")));
                cl = WithSummary(cl, @interface.Description);
                cl = WithSignature(cl, @interface);
                cl = WithRequests(cl, protocol, @interface);
                cl = WithEvents(cl, protocol, @interface);
                cl = WithEnums(cl, protocol, @interface);
                // CodeBrix fork: server-side codegen (WithServer / server listeners) is disabled —
                // this head is a pure Wayland CLIENT. The Server generator sources are kept in the
                // frozen snapshot for diffability with upstream but are never invoked.
                
                cl = cl.AddMembers(ConstructorDeclaration(cl.Identifier)
                    .AddModifiers(Token(SyntaxKind.PrivateKeyword))
                    .WithParameterList(ParameterList(
                        SeparatedList(new[]
                        {
                            Parameter(Identifier("context")).WithType(ParseTypeName("global::CodeBrix.Platform.WinUI.Runtime.Skia.Wayland.Interop.WlProxyCreationContext")),
                        }))).WithBody(Block())
                    .WithInitializer(ConstructorInitializer(SyntaxKind.BaseConstructorInitializer,
                        ArgumentList(SeparatedList(new[]
                        {
                            Argument(IdentifierName("context")),
                        })))));
                cl = cl.AddMembers(ParseMemberDeclaration(@$"
                public static {cl.Identifier} Import(WlDisplay display, IWlTargetQueue? queue, IntPtr handle, bool ownsHandle, IWlEventsListener? listener)
                {{
                    return ({cl.Identifier})WlProxy.Import(ProxyType, display, queue, handle, ownsHandle, listener);
                }}")!);
                
                ns = ns.AddMembers(cl);
            }

            return code.AddMembers(ns);
        }
    }
}
