using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Windows.ApplicationModel.Resources.Core;

namespace CodeBrix.Platform.UI.Tasks.ResourcesGenerator; //Was previously: Uno.UI.Tasks.ResourcesGenerator

/// <summary>
/// Parse Resources.resw files and generate the corresponding upri resources.
/// </summary>
/// <remarks>
/// No Android Strings.xml or UIKit Localizable.strings files are generated: this family has no Android-native or
/// UIKit-native head, and every consumer built on the Core assemblies reads the upri resources.
/// </remarks>
public class ResourcesGenerationTask_v0 : Task
{
	private const string CommentPattern = @"
	WARNING : THIS FILE HAS BEEN GENERATED BY A TOOL DO NOT UPDATE MANUALLY

	Tool name: {0}
	Source: {1}
";
	private static readonly CompositeFormat CommentCompositeFormat = CompositeFormat.Parse(CommentPattern);

	[Required]
	public ITaskItem[] Resources { get; set; }

	public string TargetPlatform { get; set; }

	public bool EnableTraceLogging { get; set; }

	public bool IsCodeBrixHead { get; set; }

	[Required]
	public string ProjectName { get; set; }

	[Required]
	public string TargetProjectDirectory { get; set; }

	[Required]
	public string OutputPath { get; set; }

	[Required]
	public string DefaultLanguage { get; set; }

	[Output]
	public ITaskItem[] GeneratedFiles { get; set; }

	public override bool Execute()
	{
		Log.LogMessage($"Generating resources for platform : {TargetPlatform}");

		try
		{
			GeneratedFiles = Resources
				// TODO: Add support for other resources file names
				.Where(resource => resource.ItemSpec?.EndsWith("resw", StringComparison.Ordinal) ?? false)
				// TODO: Merge duplicates (based on file name and qualifiers)
				.SelectMany(GetResourcesForItem)
				.Where(r => r != null)
				.ToArray();

			return true;
		}
		catch (Exception ex)
		{
			Log.LogError($"Failed to generate resources. Details: {ex.Message}");
		}

		return false;
	}

	private IEnumerable<ITaskItem> GetResourcesForItem(ITaskItem resource)
	{
		TraceLog($"Resources file found : {resource.ItemSpec}");

		var resourceCandidate = ResourceCandidate.Parse(resource.ItemSpec, resource.ItemSpec);

		var language = resourceCandidate.GetQualifierValue("language");
		if (language == null)
		{
			// TODO: Add support for resources without a language qualifier
			TraceWarning("UNOB0003", $"Ignoring resource {resource.ItemSpec}, could not determine the language");
			yield break;
		}

		TraceLog($"Language found : {language}");

		var resourceFile = resource.ItemSpec;
		var sourceLastWriteTime = new FileInfo(resourceFile).LastWriteTimeUtc;
		var resources = WindowsResourcesReader.Read(resourceFile);
		var comment = string.Format(CultureInfo.InvariantCulture, CommentCompositeFormat, this.GetType().Name, resourceFile);

		TraceLog($"{resources.Count} resources found");

		yield return GenerateCodeBrixPRIResources(language, sourceLastWriteTime, resources, comment, resource);
	}

	private ITaskItem GenerateCodeBrixPRIResources(string language, DateTime sourceLastWriteTime, Dictionary<string, string> resources, string comment, ITaskItem resource)
	{
		string buildBasePath()
		{
			if (resource.GetMetadata("TargetPath") is { Length: > 0 } targetPath)
			{
				return Path.GetDirectoryName(targetPath);
			}
			else if (Path.IsPathRooted(resource.ItemSpec))
			{
				string definingProjectDirectory = resource.GetMetadata("DefiningProjectDirectory");
				if (resource.ItemSpec.StartsWith(definingProjectDirectory, StringComparison.Ordinal))
				{
					return resource.ItemSpec.Replace(definingProjectDirectory, "");
				}
				else if (resource.ItemSpec.StartsWith(TargetProjectDirectory, StringComparison.Ordinal))
				{
					return resource.ItemSpec.Replace(TargetProjectDirectory, "");
				}
				else
				{
					return language;
				}
			}
			else
			{
				return Path.GetDirectoryName(resource.ItemSpec);
			}
		}


		var resourceMapName = Path.GetFileNameWithoutExtension(resource.ItemSpec);
		var logicalTargetPath = Path.Combine(buildBasePath(), resourceMapName + ".upri");
		var actualTargetPath = Path.Combine(OutputPath, logicalTargetPath);

		Directory.CreateDirectory(Path.GetDirectoryName(actualTargetPath));

		var targetLastWriteTime = new FileInfo(actualTargetPath).LastWriteTimeUtc;

		if (sourceLastWriteTime > targetLastWriteTime)
		{
			var libraryName = IsCodeBrixHead ? "" : ProjectName + "/";
			var qualifiedResourceMapName = libraryName + resourceMapName;

			TraceLog($"Writing resources to {actualTargetPath} ({qualifiedResourceMapName})");

			CodeBrixPRIResourcesWriter.Write(qualifiedResourceMapName, language, resources, actualTargetPath, comment);
		}
		else
		{
			TraceLog($"Skipping unmodified file {actualTargetPath}");
		}

		return new TaskItem
		(
			actualTargetPath,
			new Dictionary<string, string>()
			{
				{ "CodeBrixResourceTarget", "CodeBrix" },
				{ "LogicalName", logicalTargetPath.Replace(Path.DirectorySeparatorChar, '.') },
				{ "Language", language }
			}
		);
	}

	private void TraceLog(string message)
	{
		if (EnableTraceLogging)
		{
			Log.LogMessage(message);
		}
	}

	private void TraceWarning(string warningCode, string message)
	{
		Log.LogWarning(null, warningCode, null, null, 0, 0, 0, 0, message);
	}
}
