using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: InternalsVisibleTo("CodeBrix.Platform.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Wasm")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RuntimeTests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RuntimeTests.Windows")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Composition.Core")]

[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Wpf")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Win32")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Tizen")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Linux.FrameBuffer")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Linux.FrameBuffer.Emulated")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.WebAssembly.Browser")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Android")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.AppleUIKit")]

[assembly: InternalsVisibleTo("SamplesApp")]
[assembly: InternalsVisibleTo("SamplesApp.Windows")]
[assembly: InternalsVisibleTo("SamplesApp.Droid")]
[assembly: InternalsVisibleTo("SamplesApp.macOS")]
[assembly: InternalsVisibleTo("SamplesApp.Wasm")]
[assembly: InternalsVisibleTo("SamplesApp.Skia")]

[assembly: InternalsVisibleTo("CodeBrix.Platform.WinUI.Graphics2DSK")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.WinUI.Graphics2DSK.Core")]
// The Skia-canvas host seam of the SkiaSharp views add-in (Compositor.GetSharedCompositor).
[assembly: InternalsVisibleTo("CodeBrix.Platform.SkiaSharp.Views.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.WinUI.Graphics3DGL")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.WinUI.Graphics3DGL.Core")]

[assembly: InternalsVisibleTo("CodeBrix.PlatformIslandsSamplesApp")]
[assembly: InternalsVisibleTo("CodeBrix.PlatformIslandsSamplesApp.Skia")]

// CodeBrix.Platform.UI.Composition.Core (the platform-neutral Core assembly this file is compiled into since the Core/Skia split):
// and, by rule (decision P4), the CodeBrix.Android and CodeBrix.Mobile assemblies (and their tests) for the same library.
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Composition.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Composition.Tests")]

// The grants the pre-split assembly carried in AssemblyInfo.skia.cs (the heads and Skia-side test hosts), which
// reach Core internals too; the Core assembly keeps the union of the old lists (decision P4).
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.MacOS")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.X11")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Wayland")]

// The host-free Core suite (src/Platform.UI.Core.Tests) registers test doubles for the platform contracts.
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Core.Tests")]

// Element handler seam (WPH1, decisions D-P3 and the AP1-B cross-assembly rule): the CodeBrix.Android and CodeBrix.Mobile
// counterparts (and their tests) of every Skia-side assembly granted above - the framework Skia twins and the add-ins'
// platform assemblies - so that a platform implementation of a Core contract, or a platform handler, compiles against the
// same internals the Skia side uses. This Core assembly also grants every add-in's Android and Mobile name (D-P3).
[assembly: InternalsVisibleTo("CodeBrix.Android.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics2DSK")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics2DSK.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics2DSK")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics2DSK.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics3DGL")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Graphics3DGL.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics3DGL")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Graphics3DGL.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.AppSettings")]
[assembly: InternalsVisibleTo("CodeBrix.Android.AppSettings.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.AppSettings")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.AppSettings.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.SkiaSharp.Views")]
[assembly: InternalsVisibleTo("CodeBrix.Android.SkiaSharp.Views.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.SkiaSharp.Views")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.SkiaSharp.Views.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AdvancedTextEdit")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AdvancedTextEdit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AdvancedTextEdit")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AdvancedTextEdit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AudioPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.AudioPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AudioPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.AudioPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.CommandBar")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.CommandBar.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.CommandBar")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.CommandBar.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.FlexPanel")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.FlexPanel.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.FlexPanel")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.FlexPanel.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.MediaPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.MediaPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.MediaPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.MediaPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.PlotterView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.PlotterView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.PlotterView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.PlotterView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TerminalView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TerminalView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TerminalView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TerminalView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TextLayout")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TextLayout.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TextLayout")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TextLayout.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.VideoPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.VideoPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.VideoPlayer")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.VideoPlayer.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.WebView")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.WebView.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.WebView")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.WebView.Tests")]
[assembly: System.Reflection.AssemblyMetadata("IsTrimmable", "True")]

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.PlayTest")]
