using global::System.Reflection;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;

[assembly: InternalsVisibleTo("CodeBrix.Platform.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Wasm")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Wasm")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Foundation")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Foundation.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Foundation.Wasm")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Wasm.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.Foundation.Runtime.WebAssembly")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Toolkit.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RemoteControl")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme.v1")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme.v1.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme.v2")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.FluentTheme.v2.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.GooglePlay")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Lottie.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Svg.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Svg.Skia")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.MacOS")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Wpf")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Win32")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Win32.Support")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Maps")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Tizen")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Linux.FrameBuffer")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Linux.FrameBuffer.Emulated")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.X11")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Wayland")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.WebAssembly.Browser")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.Android")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.AppleUIKit")]
[assembly: InternalsVisibleTo("SamplesApp.Skia.Tizen")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.RuntimeTests")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Foldable")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.MediaPlayer.WebAssembly")]
[assembly: InternalsVisibleTo("SamplesApp.Wasm")]
[assembly: InternalsVisibleTo("SamplesApp.Skia")]
[assembly: InternalsVisibleTo("SamplesApp")]
[assembly: InternalsVisibleTo("SamplesApp.iOS")]
[assembly: InternalsVisibleTo("SamplesApp.Droid")]
[assembly: InternalsVisibleTo("SamplesApp.MacOS")]
[assembly: InternalsVisibleTo("CodeBrix.PlatformIslandsSamplesApp.Skia")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Adapter.Microsoft.Extensions.Logging")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Adapter.Microsoft.Extensions.Logging.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Composition.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Dispatching")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Dispatching.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia")]

// CodeBrix.Platform.Foundation.Logging.Core (the platform-neutral Core assembly this file is compiled into since the Core/Skia split):
// and, by rule (decision P4), the CodeBrix.Android and CodeBrix.Mobile assemblies (and their tests) for the same library.
[assembly: InternalsVisibleTo("CodeBrix.Android.Foundation.Logging")]
[assembly: InternalsVisibleTo("CodeBrix.Android.Foundation.Logging.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.Foundation.Logging")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.Foundation.Logging.Tests")]

// Element handler seam (WPH1, decisions D-P3 and the AP1-B cross-assembly rule): the CodeBrix.Android and CodeBrix.Mobile
// counterparts (and their tests) of every Skia-side assembly granted above - the framework Skia twins and the add-ins'
// platform assemblies - so that a platform implementation of a Core contract, or a platform handler, compiles against the
// same internals the Skia side uses.
[assembly: InternalsVisibleTo("CodeBrix.Android.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android")]
[assembly: InternalsVisibleTo("CodeBrix.Android.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Toolkit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Toolkit.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Lottie.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Svg.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Composition.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Composition")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Composition.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Dispatching")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.Dispatching.Tests")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Dispatching")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.Dispatching.Tests")]

// The shared text engine (WPE1 C5): its second copy is compiled into the TextLayout add-in's Core assembly and logs like
// the framework's copy does; by rule (decision P4) also the CodeBrix.Android and CodeBrix.Mobile assemblies for it.
[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.TextLayout.Core")]
[assembly: InternalsVisibleTo("CodeBrix.Android.UI.TextLayout")]
[assembly: InternalsVisibleTo("CodeBrix.Mobile.UI.TextLayout")]

[assembly: InternalsVisibleTo("CodeBrix.Platform.UI.Runtime.Skia.PlayTest")]
