using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using CodeBrix.Platform.UI.SourceGenerators.ImplementedRoutedEvents;
using CodeBrix.Platform.UI.SourceGenerators.Tests.Verifiers;

namespace CodeBrix.Platform.UI.SourceGenerators.Tests.ImplementedRoutedEventsGeneratorTests //Was previously: Uno.UI.SourceGenerators.Tests.ImplementedRoutedEventsGeneratorTests
{
	using Verify = CSharpSourceGeneratorVerifier<ImplementedRoutedEventsGenerator>;

	[TestClass]
	public class Given_ImplementedRoutedEventsGenerator
	{
		private async Task TestGeneratorAsync(string inputSource, params GeneratedFile[] generatedFiles)
		{
			var test = new Verify.Test
			{
				// Use the local de-Uno'd assemblies (which provide the CodeBrix.Platform.* namespaces emitted by
				// the generator) rather than the Uno.WinUI NuGet (which only provides the Uno.* namespaces).
				ReferenceAssemblies = _Dotnet.Current.ReferenceAssemblies,
				TestState =
				{
					Sources = { inputSource },
				},
			};
			test.TestState.AdditionalReferences.AddRange(CodeBrixAssemblyHelper.LoadAssemblies());
			// Generated-file hint paths are authored with Windows separators; align to the running OS
			// ('\' on Windows, '/' elsewhere) so the expected file list matches on every platform.
			test.TestState.GeneratedSources.AddRange(generatedFiles.Select(f => (f.Path.Replace('\\', System.IO.Path.DirectorySeparatorChar), f.Source)));
			await test.RunAsync();
		}

		[TestMethod]
		public async Task Given_NonGeneric_Control_In_Global_Namespace()
		{
			const string inputSource = @"
using Microsoft.UI.Xaml.Controls;

public partial class MyAwesomeControl : Control
{
}
";
			const string expectedCode = @"// <auto-generated>
partial class MyAwesomeControl
{
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	private static global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag __codebrix_ImplementedRoutedEvents = global::CodeBrix.Platform.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(MyAwesomeControl),
		global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag.None
	);
}
";
			await TestGeneratorAsync(
				inputSource,
				new GeneratedFile(
					@"CodeBrix.Platform.UI.SourceGenerators\CodeBrix.Platform.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyAwesomeControl_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}

		[TestMethod]
		public async Task Given_Generic_Control_In_Global_Namespace()
		{
			const string inputSource = @"
using Microsoft.UI.Xaml.Controls;

public partial class MyAwesomeControl<T> : Control
{
}
";
			const string expectedCode = @"// <auto-generated>
partial class MyAwesomeControl<T>
{
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	private static global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag __codebrix_ImplementedRoutedEvents = global::CodeBrix.Platform.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
		typeof(MyAwesomeControl<T>),
		global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag.None
	);
}
";
			await TestGeneratorAsync(
				inputSource,
				new GeneratedFile(
					@"CodeBrix.Platform.UI.SourceGenerators\CodeBrix.Platform.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyAwesomeControl-1_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}

		[TestMethod]
		public async Task Given_Generic_Control_In_Non_Global_Namespace()
		{
			const string inputSource = @"
using Microsoft.UI.Xaml.Controls;

namespace MyControls.Test
{
	public partial class MyAwesomeControl<T> : Control
	{
	}
}
";
			const string expectedCode = @"// <auto-generated>
namespace MyControls.Test
{
	partial class MyAwesomeControl<T>
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag __codebrix_ImplementedRoutedEvents = global::CodeBrix.Platform.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
			typeof(MyAwesomeControl<T>),
			global::CodeBrix.Platform.UI.Xaml.RoutedEventFlag.None
		);
	}
}
";
			await TestGeneratorAsync(
				inputSource,
				new GeneratedFile(
					@"CodeBrix.Platform.UI.SourceGenerators\CodeBrix.Platform.UI.SourceGenerators.ImplementedRoutedEvents.ImplementedRoutedEventsGenerator\MyControls.Test.MyAwesomeControl-1_ImplementedRoutedEvents.g.cs",
					expectedCode));
		}
	}

	public class GeneratedFile
	{
		public GeneratedFile(string path, string source)
		{
			Path = path;
			// Sha256 explicit so expected matches what the running compilation produces.
			// Roslyn 5's CompilationOptions.ChecksumAlgorithm defaults to Sha256, but the
			// SourceText.From(string, Encoding) overload still defaults to Sha1 — pinning
			// Sha256 here aligns the expected SourceText with the generator's actual output.
			Source = SourceText.From(source, Encoding.UTF8, SourceHashAlgorithm.Sha256);
		}

		public string Path { get; set; }

		public SourceText Source { get; set; }
	}
}
