#nullable enable

using System.Collections.Generic;

namespace CodeBrix.Platform.UI.Localization;

public static partial class PlatformStrings
{
	static IReadOnlyList<PlatformStringSet> SouthernEurope =>
	[
		new PlatformStringSet
		{
			Code = "es",
			Cancel = "Cancelar",
			Create = "Crear",
			FolderNamePlaceholder = "Nombre de la carpeta",
			KeepEditing = "Seguir editando",
			NameLabel = "Nombre:",
			NewFolder = "Nueva carpeta",
			NoItems = "Sin elementos",
			Open = "Abrir",
			OpenFileTitle = "Abrir archivo",
			Replace = "Reemplazar",
			ReplaceFileFormat = "¿Reemplazar «{0}»?",
			Save = "Guardar",
			SaveFileTitle = "Guardar archivo",
			SelectFolderTitle = "Seleccionar carpeta",
			Ok = "Aceptar",
			Yes = "Sí",
			No = "No",

			InformationTitle = "Información",
			ErrorTitle = "Error",
			ErrorOccurredLabel = "Se ha producido un error:",
			DetailsLabel = "Detalles:",
			ConfirmTitle = "¿Está seguro?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Intro",
			KeyShift = "Mayús",
			KeyShiftUpper = "MAYÚS",
			KeyBackspace = "Retr",
		},

		new PlatformStringSet
		{
			Code = "pt",
			Cancel = "Cancelar",
			Create = "Criar",
			FolderNamePlaceholder = "Nome da pasta",
			KeepEditing = "Continuar a editar",
			NameLabel = "Nome:",
			NewFolder = "Nova pasta",
			NoItems = "Sem itens",
			Open = "Abrir",
			OpenFileTitle = "Abrir ficheiro",
			Replace = "Substituir",
			ReplaceFileFormat = "Substituir «{0}»?",
			Save = "Guardar",
			SaveFileTitle = "Guardar ficheiro",
			SelectFolderTitle = "Selecionar pasta",
			Ok = "OK",
			Yes = "Sim",
			No = "Não",

			InformationTitle = "Informação",
			ErrorTitle = "Erro",
			ErrorOccurredLabel = "Ocorreu um erro:",
			DetailsLabel = "Detalhes:",
			ConfirmTitle = "Tem a certeza?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Retr",
		},

		new PlatformStringSet
		{
			Code = "it",
			Cancel = "Annulla",
			Create = "Crea",
			FolderNamePlaceholder = "Nome cartella",
			KeepEditing = "Continua a modificare",
			NameLabel = "Nome:",
			NewFolder = "Nuova cartella",
			NoItems = "Nessun elemento",
			Open = "Apri",
			OpenFileTitle = "Apri file",
			Replace = "Sostituisci",
			ReplaceFileFormat = "Sostituire «{0}»?",
			Save = "Salva",
			SaveFileTitle = "Salva file",
			SelectFolderTitle = "Seleziona cartella",
			Ok = "OK",
			Yes = "Sì",
			No = "No",

			InformationTitle = "Informazioni",
			ErrorTitle = "Errore",
			ErrorOccurredLabel = "Si è verificato un errore:",
			DetailsLabel = "Dettagli:",
			ConfirmTitle = "Sei sicuro?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Invio",
			KeyShift = "Maiusc",
			KeyShiftUpper = "MAIUSC",
			KeyBackspace = "Canc",
		},

		new PlatformStringSet
		{
			Code = "mt",
			Cancel = "Ikkanċella",
			Create = "Oħloq",
			FolderNamePlaceholder = "Isem tal-katalgu",
			KeepEditing = "Kompli editja",
			NameLabel = "Isem:",
			NewFolder = "Katalgu ġdid",
			NoItems = "L-ebda oġġett",
			Open = "Iftaħ",
			OpenFileTitle = "Iftaħ fajl",
			Replace = "Issostitwixxi",
			ReplaceFileFormat = "Tissostitwixxi “{0}”?",
			Save = "Issejvja",
			SaveFileTitle = "Issejvja l-fajl",
			SelectFolderTitle = "Agħżel katalgu",
			Ok = "OK",
			Yes = "Iva",
			No = "Le",

			InformationTitle = "Informazzjoni",
			ErrorTitle = "Żball",
			ErrorOccurredLabel = "Seħħ żball:",
			DetailsLabel = "Dettalji:",
			ConfirmTitle = "Żgur?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Bksp",
		},

		new PlatformStringSet
		{
			Code = "sq",
			Cancel = "Anulo",
			Create = "Krijo",
			FolderNamePlaceholder = "Emri i dosjes",
			KeepEditing = "Vazhdo redaktimin",
			NameLabel = "Emri:",
			NewFolder = "Dosje e re",
			NoItems = "Asnjë element",
			Open = "Hap",
			OpenFileTitle = "Hap skedar",
			Replace = "Zëvendëso",
			ReplaceFileFormat = "Të zëvendësohet “{0}”?",
			Save = "Ruaj",
			SaveFileTitle = "Ruaj skedarin",
			SelectFolderTitle = "Zgjidh dosjen",
			Ok = "OK",
			Yes = "Po",
			No = "Jo",

			InformationTitle = "Informacion",
			ErrorTitle = "Gabim",
			ErrorOccurredLabel = "Ndodhi një gabim:",
			DetailsLabel = "Detajet:",
			ConfirmTitle = "Jeni i sigurt?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Bksp",
		},

		new PlatformStringSet
		{
			Code = "tr",
			Cancel = "İptal",
			Create = "Oluştur",
			FolderNamePlaceholder = "Klasör adı",
			KeepEditing = "Düzenlemeye devam et",
			NameLabel = "Ad:",
			NewFolder = "Yeni klasör",
			NoItems = "Öğe yok",
			Open = "Aç",
			OpenFileTitle = "Dosya aç",
			Replace = "Değiştir",
			ReplaceFileFormat = "“{0}” değiştirilsin mi?",
			Save = "Kaydet",
			SaveFileTitle = "Dosyayı kaydet",
			SelectFolderTitle = "Klasör seç",
			Ok = "Tamam",
			Yes = "Evet",
			No = "Hayır",

			InformationTitle = "Bilgi",
			ErrorTitle = "Hata",
			ErrorOccurredLabel = "Bir hata oluştu:",
			DetailsLabel = "Ayrıntılar:",
			ConfirmTitle = "Emin misiniz?",
			KeyAbc = "ABC",
			KeyTab = "Sekme",
			KeyEnter = "Enter",
			KeyShift = "Üst Krkt",
			KeyShiftUpper = "ÜST KRKT",
			KeyBackspace = "Geri",
		},

		new PlatformStringSet
		{
			Code = "el",
			Cancel = "Άκυρο",
			Create = "Δημιουργία",
			FolderNamePlaceholder = "Όνομα φακέλου",
			KeepEditing = "Συνέχεια επεξεργασίας",
			NameLabel = "Όνομα:",
			NewFolder = "Νέος φάκελος",
			NoItems = "Κανένα στοιχείο",
			Open = "Άνοιγμα",
			OpenFileTitle = "Άνοιγμα αρχείου",
			Replace = "Αντικατάσταση",
			ReplaceFileFormat = "Αντικατάσταση του «{0}»;",
			Save = "Αποθήκευση",
			SaveFileTitle = "Αποθήκευση αρχείου",
			SelectFolderTitle = "Επιλογή φακέλου",
			Ok = "OK",
			Yes = "Ναι",
			No = "Όχι",

			InformationTitle = "Πληροφορίες",
			ErrorTitle = "Σφάλμα",
			ErrorOccurredLabel = "Παρουσιάστηκε σφάλμα:",
			DetailsLabel = "Λεπτομέρειες:",
			ConfirmTitle = "Είστε σίγουροι;",
			KeyAbc = "ΑΒΓ",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Διαγρ",
		},
	];
}
