#nullable enable

using System.Collections.Generic;

namespace CodeBrix.Platform.UI.Localization;

public static partial class PlatformStrings
{
	// English is also the fallback for every language without a set of its own,
	// so it must stay complete and first.
	static IReadOnlyList<PlatformStringSet> WesternEurope =>
	[
		new PlatformStringSet
		{
			Code = "en",
			Cancel = "Cancel",
			Create = "Create",
			FolderNamePlaceholder = "Folder name",
			KeepEditing = "Keep editing",
			NameLabel = "Name:",
			NavigateUp = "Up",
			NewFolder = "New folder",
			NoItems = "No items",
			Open = "Open",
			OpenFileTitle = "Open file",
			Replace = "Replace",
			ReplaceFileFormat = "Replace “{0}”?",
			Save = "Save",
			SaveFileTitle = "Save file",
			SelectFolderTitle = "Select folder",
			Ok = "OK",
			Yes = "Yes",
			No = "No",

			InformationTitle = "Information",
			ErrorTitle = "Error",
			ErrorOccurredLabel = "An error occurred:",
			DetailsLabel = "Details:",
			ConfirmTitle = "Are you sure?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Bksp",
		},

		// British English differs from American in none of these words; the
		// set exists so the layout id resolves exactly rather than by fallback.
		new PlatformStringSet
		{
			Code = "en-GB",
			Cancel = "Cancel",
			Create = "Create",
			FolderNamePlaceholder = "Folder name",
			KeepEditing = "Keep editing",
			NameLabel = "Name:",
			NavigateUp = "Up",
			NewFolder = "New folder",
			NoItems = "No items",
			Open = "Open",
			OpenFileTitle = "Open file",
			Replace = "Replace",
			ReplaceFileFormat = "Replace “{0}”?",
			Save = "Save",
			SaveFileTitle = "Save file",
			SelectFolderTitle = "Select folder",
			Ok = "OK",
			Yes = "Yes",
			No = "No",

			InformationTitle = "Information",
			ErrorTitle = "Error",
			ErrorOccurredLabel = "An error occurred:",
			DetailsLabel = "Details:",
			ConfirmTitle = "Are you sure?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Bksp",
		},

		new PlatformStringSet
		{
			Code = "de",
			Cancel = "Abbrechen",
			Create = "Erstellen",
			FolderNamePlaceholder = "Ordnername",
			KeepEditing = "Weiter bearbeiten",
			NameLabel = "Name:",
			NavigateUp = "Nach oben",
			NewFolder = "Neuer Ordner",
			NoItems = "Keine Einträge",
			Open = "Öffnen",
			OpenFileTitle = "Datei öffnen",
			Replace = "Ersetzen",
			ReplaceFileFormat = "„{0}“ ersetzen?",
			Save = "Speichern",
			SaveFileTitle = "Datei speichern",
			SelectFolderTitle = "Ordner auswählen",
			Ok = "OK",
			Yes = "Ja",
			No = "Nein",

			InformationTitle = "Information",
			ErrorTitle = "Fehler",
			ErrorOccurredLabel = "Ein Fehler ist aufgetreten:",
			DetailsLabel = "Details:",
			ConfirmTitle = "Sind Sie sicher?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Umschalt",
			KeyShiftUpper = "UMSCHALT",
			KeyBackspace = "Rück",
		},

		// Swiss German takes Swiss quotation marks; none of these words carry
		// an ß, so the Swiss spelling rule does not bite here.
		new PlatformStringSet
		{
			Code = "de-CH",
			Cancel = "Abbrechen",
			Create = "Erstellen",
			FolderNamePlaceholder = "Ordnername",
			KeepEditing = "Weiter bearbeiten",
			NameLabel = "Name:",
			NavigateUp = "Nach oben",
			NewFolder = "Neuer Ordner",
			NoItems = "Keine Einträge",
			Open = "Öffnen",
			OpenFileTitle = "Datei öffnen",
			Replace = "Ersetzen",
			ReplaceFileFormat = "«{0}» ersetzen?",
			Save = "Speichern",
			SaveFileTitle = "Datei speichern",
			SelectFolderTitle = "Ordner auswählen",
			Ok = "OK",
			Yes = "Ja",
			No = "Nein",

			InformationTitle = "Information",
			ErrorTitle = "Fehler",
			ErrorOccurredLabel = "Ein Fehler ist aufgetreten:",
			DetailsLabel = "Details:",
			ConfirmTitle = "Sind Sie sicher?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Umschalt",
			KeyShiftUpper = "UMSCHALT",
			KeyBackspace = "Rück",
		},

		new PlatformStringSet
		{
			Code = "fr",
			Cancel = "Annuler",
			Create = "Créer",
			FolderNamePlaceholder = "Nom du dossier",
			KeepEditing = "Continuer la modification",
			NameLabel = "Nom :",
			NavigateUp = "Remonter",
			NewFolder = "Nouveau dossier",
			NoItems = "Aucun élément",
			Open = "Ouvrir",
			OpenFileTitle = "Ouvrir un fichier",
			Replace = "Remplacer",
			ReplaceFileFormat = "Remplacer « {0} » ?",
			Save = "Enregistrer",
			SaveFileTitle = "Enregistrer le fichier",
			SelectFolderTitle = "Sélectionner un dossier",
			Ok = "OK",
			Yes = "Oui",
			No = "Non",

			InformationTitle = "Information",
			ErrorTitle = "Erreur",
			ErrorOccurredLabel = "Une erreur s'est produite :",
			DetailsLabel = "Détails :",
			ConfirmTitle = "Êtes-vous sûr ?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Entrée",
			KeyShift = "Maj",
			KeyShiftUpper = "MAJ",
			KeyBackspace = "Ret",
		},

		new PlatformStringSet
		{
			Code = "fr-BE",
			Cancel = "Annuler",
			Create = "Créer",
			FolderNamePlaceholder = "Nom du dossier",
			KeepEditing = "Continuer la modification",
			NameLabel = "Nom :",
			NavigateUp = "Remonter",
			NewFolder = "Nouveau dossier",
			NoItems = "Aucun élément",
			Open = "Ouvrir",
			OpenFileTitle = "Ouvrir un fichier",
			Replace = "Remplacer",
			ReplaceFileFormat = "Remplacer « {0} » ?",
			Save = "Enregistrer",
			SaveFileTitle = "Enregistrer le fichier",
			SelectFolderTitle = "Sélectionner un dossier",
			Ok = "OK",
			Yes = "Oui",
			No = "Non",

			InformationTitle = "Information",
			ErrorTitle = "Erreur",
			ErrorOccurredLabel = "Une erreur s'est produite :",
			DetailsLabel = "Détails :",
			ConfirmTitle = "Êtes-vous sûr ?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Entrée",
			KeyShift = "Maj",
			KeyShiftUpper = "MAJ",
			KeyBackspace = "Ret",
		},

		new PlatformStringSet
		{
			Code = "fr-CH",
			Cancel = "Annuler",
			Create = "Créer",
			FolderNamePlaceholder = "Nom du dossier",
			KeepEditing = "Continuer la modification",
			NameLabel = "Nom :",
			NavigateUp = "Remonter",
			NewFolder = "Nouveau dossier",
			NoItems = "Aucun élément",
			Open = "Ouvrir",
			OpenFileTitle = "Ouvrir un fichier",
			Replace = "Remplacer",
			ReplaceFileFormat = "Remplacer «{0}» ?",
			Save = "Enregistrer",
			SaveFileTitle = "Enregistrer le fichier",
			SelectFolderTitle = "Sélectionner un dossier",
			Ok = "OK",
			Yes = "Oui",
			No = "Non",

			InformationTitle = "Information",
			ErrorTitle = "Erreur",
			ErrorOccurredLabel = "Une erreur s'est produite :",
			DetailsLabel = "Détails :",
			ConfirmTitle = "Êtes-vous sûr ?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Entrée",
			KeyShift = "Maj",
			KeyShiftUpper = "MAJ",
			KeyBackspace = "Ret",
		},

		new PlatformStringSet
		{
			Code = "nl",
			Cancel = "Annuleren",
			Create = "Maken",
			FolderNamePlaceholder = "Mapnaam",
			KeepEditing = "Verder bewerken",
			NameLabel = "Naam:",
			NavigateUp = "Omhoog",
			NewFolder = "Nieuwe map",
			NoItems = "Geen items",
			Open = "Openen",
			OpenFileTitle = "Bestand openen",
			Replace = "Vervangen",
			ReplaceFileFormat = "„{0}” vervangen?",
			Save = "Opslaan",
			SaveFileTitle = "Bestand opslaan",
			SelectFolderTitle = "Map selecteren",
			Ok = "OK",
			Yes = "Ja",
			No = "Nee",

			InformationTitle = "Informatie",
			ErrorTitle = "Fout",
			ErrorOccurredLabel = "Er is een fout opgetreden:",
			DetailsLabel = "Details:",
			ConfirmTitle = "Weet u het zeker?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Wis",
		},
	];
}
