#nullable enable

using System.Collections.Generic;

namespace CodeBrix.Platform.UI.Localization;

public static partial class PlatformStrings
{
	static IReadOnlyList<PlatformStringSet> CentralEurope =>
	[
		new PlatformStringSet
		{
			Code = "pl",
			Cancel = "Anuluj",
			Create = "Utwórz",
			FolderNamePlaceholder = "Nazwa folderu",
			KeepEditing = "Kontynuuj edycję",
			NameLabel = "Nazwa:",
			NavigateUp = "W górę",
			NewFolder = "Nowy folder",
			NoItems = "Brak elementów",
			Open = "Otwórz",
			OpenFileTitle = "Otwórz plik",
			Replace = "Zamień",
			ReplaceFileFormat = "Zamienić „{0}”?",
			Save = "Zapisz",
			SaveFileTitle = "Zapisz plik",
			SelectFolderTitle = "Wybierz folder",
			Ok = "OK",
			Yes = "Tak",
			No = "Nie",

			InformationTitle = "Informacja",
			ErrorTitle = "Błąd",
			ErrorOccurredLabel = "Wystąpił błąd:",
			DetailsLabel = "Szczegóły:",
			ConfirmTitle = "Czy na pewno?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Cofnij",
		},

		new PlatformStringSet
		{
			Code = "cs",
			Cancel = "Zrušit",
			Create = "Vytvořit",
			FolderNamePlaceholder = "Název složky",
			KeepEditing = "Pokračovat v úpravách",
			NameLabel = "Název:",
			NavigateUp = "Nahoru",
			NewFolder = "Nová složka",
			NoItems = "Žádné položky",
			Open = "Otevřít",
			OpenFileTitle = "Otevřít soubor",
			Replace = "Nahradit",
			ReplaceFileFormat = "Nahradit „{0}“?",
			Save = "Uložit",
			SaveFileTitle = "Uložit soubor",
			SelectFolderTitle = "Vybrat složku",
			Ok = "OK",
			Yes = "Ano",
			No = "Ne",

			InformationTitle = "Informace",
			ErrorTitle = "Chyba",
			ErrorOccurredLabel = "Došlo k chybě:",
			DetailsLabel = "Podrobnosti:",
			ConfirmTitle = "Opravdu?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Zpět",
		},

		new PlatformStringSet
		{
			Code = "sk",
			Cancel = "Zrušiť",
			Create = "Vytvoriť",
			FolderNamePlaceholder = "Názov priečinka",
			KeepEditing = "Pokračovať v úpravách",
			NameLabel = "Názov:",
			NavigateUp = "Hore",
			NewFolder = "Nový priečinok",
			NoItems = "Žiadne položky",
			Open = "Otvoriť",
			OpenFileTitle = "Otvoriť súbor",
			Replace = "Nahradiť",
			ReplaceFileFormat = "Nahradiť „{0}“?",
			Save = "Uložiť",
			SaveFileTitle = "Uložiť súbor",
			SelectFolderTitle = "Vybrať priečinok",
			Ok = "OK",
			Yes = "Áno",
			No = "Nie",

			InformationTitle = "Informácie",
			ErrorTitle = "Chyba",
			ErrorOccurredLabel = "Vyskytla sa chyba:",
			DetailsLabel = "Podrobnosti:",
			ConfirmTitle = "Naozaj?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Späť",
		},

		new PlatformStringSet
		{
			Code = "hu",
			Cancel = "Mégse",
			Create = "Létrehozás",
			FolderNamePlaceholder = "Mappa neve",
			KeepEditing = "Szerkesztés folytatása",
			NameLabel = "Név:",
			NavigateUp = "Fel",
			NewFolder = "Új mappa",
			NoItems = "Nincsenek elemek",
			Open = "Megnyitás",
			OpenFileTitle = "Fájl megnyitása",
			Replace = "Csere",
			ReplaceFileFormat = "Lecseréli a(z) „{0}” fájlt?",
			Save = "Mentés",
			SaveFileTitle = "Fájl mentése",
			SelectFolderTitle = "Mappa kiválasztása",
			Ok = "OK",
			Yes = "Igen",
			No = "Nem",

			InformationTitle = "Információ",
			ErrorTitle = "Hiba",
			ErrorOccurredLabel = "Hiba történt:",
			DetailsLabel = "Részletek:",
			ConfirmTitle = "Biztos benne?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Törlés",
		},

		new PlatformStringSet
		{
			Code = "ro",
			Cancel = "Anulare",
			Create = "Creare",
			FolderNamePlaceholder = "Numele folderului",
			KeepEditing = "Continuă editarea",
			NameLabel = "Nume:",
			NavigateUp = "Sus",
			NewFolder = "Folder nou",
			NoItems = "Niciun element",
			Open = "Deschide",
			OpenFileTitle = "Deschide fișier",
			Replace = "Înlocuiește",
			ReplaceFileFormat = "Înlocuiți „{0}”?",
			Save = "Salvează",
			SaveFileTitle = "Salvează fișierul",
			SelectFolderTitle = "Selectați folderul",
			Ok = "OK",
			Yes = "Da",
			No = "Nu",

			InformationTitle = "Informații",
			ErrorTitle = "Eroare",
			ErrorOccurredLabel = "A apărut o eroare:",
			DetailsLabel = "Detalii:",
			ConfirmTitle = "Sigur?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Șterge",
		},

		new PlatformStringSet
		{
			Code = "hr",
			Cancel = "Odustani",
			Create = "Stvori",
			FolderNamePlaceholder = "Naziv mape",
			KeepEditing = "Nastavi uređivanje",
			NameLabel = "Naziv:",
			NavigateUp = "Gore",
			NewFolder = "Nova mapa",
			NoItems = "Nema stavki",
			Open = "Otvori",
			OpenFileTitle = "Otvori datoteku",
			Replace = "Zamijeni",
			ReplaceFileFormat = "Zamijeniti „{0}”?",
			Save = "Spremi",
			SaveFileTitle = "Spremi datoteku",
			SelectFolderTitle = "Odaberi mapu",
			Ok = "U redu",
			Yes = "Da",
			No = "Ne",

			InformationTitle = "Informacije",
			ErrorTitle = "Pogreška",
			ErrorOccurredLabel = "Došlo je do pogreške:",
			DetailsLabel = "Pojedinosti:",
			ConfirmTitle = "Jeste li sigurni?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Briši",
		},

		// Serbian written in Latin script. Its own set rather than a fallback
		// to "sr": the words are the same language but not the same letters.
		new PlatformStringSet
		{
			Code = "sr-Latn",
			Cancel = "Otkaži",
			Create = "Napravi",
			FolderNamePlaceholder = "Naziv fascikle",
			KeepEditing = "Nastavi uređivanje",
			NameLabel = "Naziv:",
			NavigateUp = "Gore",
			NewFolder = "Nova fascikla",
			NoItems = "Nema stavki",
			Open = "Otvori",
			OpenFileTitle = "Otvori datoteku",
			Replace = "Zameni",
			ReplaceFileFormat = "Zameniti „{0}”?",
			Save = "Sačuvaj",
			SaveFileTitle = "Sačuvaj datoteku",
			SelectFolderTitle = "Izaberi fasciklu",
			Ok = "U redu",
			Yes = "Da",
			No = "Ne",

			InformationTitle = "Informacije",
			ErrorTitle = "Greška",
			ErrorOccurredLabel = "Došlo je do greške:",
			DetailsLabel = "Detalji:",
			ConfirmTitle = "Da li ste sigurni?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Briši",
		},
	];
}
