#nullable enable

using System.Collections.Generic;

namespace CodeBrix.Platform.UI.Localization;

public static partial class PlatformStrings
{
	// KeyAbc is spelled in each language's own alphabet — "АБВ" for the
	// Cyrillic layouts — the way the letters key is labelled on a phone.
	static IReadOnlyList<PlatformStringSet> Cyrillic =>
	[
		new PlatformStringSet
		{
			Code = "ru",
			Cancel = "Отмена",
			Create = "Создать",
			FolderNamePlaceholder = "Имя папки",
			KeepEditing = "Продолжить правку",
			NameLabel = "Имя:",
			NewFolder = "Новая папка",
			NoItems = "Нет элементов",
			Open = "Открыть",
			OpenFileTitle = "Открыть файл",
			Replace = "Заменить",
			ReplaceFileFormat = "Заменить «{0}»?",
			Save = "Сохранить",
			SaveFileTitle = "Сохранить файл",
			SelectFolderTitle = "Выбрать папку",
			Ok = "ОК",
			Yes = "Да",
			No = "Нет",

			InformationTitle = "Информация",
			ErrorTitle = "Ошибка",
			ErrorOccurredLabel = "Произошла ошибка:",
			DetailsLabel = "Подробности:",
			ConfirmTitle = "Вы уверены?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Ввод",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Стереть",
		},

		new PlatformStringSet
		{
			Code = "uk",
			Cancel = "Скасувати",
			Create = "Створити",
			FolderNamePlaceholder = "Назва теки",
			KeepEditing = "Продовжити редагування",
			NameLabel = "Назва:",
			NewFolder = "Нова тека",
			NoItems = "Немає елементів",
			Open = "Відкрити",
			OpenFileTitle = "Відкрити файл",
			Replace = "Замінити",
			ReplaceFileFormat = "Замінити «{0}»?",
			Save = "Зберегти",
			SaveFileTitle = "Зберегти файл",
			SelectFolderTitle = "Вибрати теку",
			Ok = "ОК",
			Yes = "Так",
			No = "Ні",

			InformationTitle = "Інформація",
			ErrorTitle = "Помилка",
			ErrorOccurredLabel = "Сталася помилка:",
			DetailsLabel = "Подробиці:",
			ConfirmTitle = "Ви впевнені?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Ввід",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Стерти",
		},

		new PlatformStringSet
		{
			Code = "be",
			Cancel = "Скасаваць",
			Create = "Стварыць",
			FolderNamePlaceholder = "Назва папкі",
			KeepEditing = "Працягнуць рэдагаванне",
			NameLabel = "Назва:",
			NewFolder = "Новая папка",
			NoItems = "Няма элементаў",
			Open = "Адкрыць",
			OpenFileTitle = "Адкрыць файл",
			Replace = "Замяніць",
			ReplaceFileFormat = "Замяніць «{0}»?",
			Save = "Захаваць",
			SaveFileTitle = "Захаваць файл",
			SelectFolderTitle = "Выбраць папку",
			Ok = "ОК",
			Yes = "Так",
			No = "Не",

			InformationTitle = "Інфармацыя",
			ErrorTitle = "Памылка",
			ErrorOccurredLabel = "Адбылася памылка:",
			DetailsLabel = "Падрабязнасці:",
			ConfirmTitle = "Вы ўпэўнены?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Увод",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Сцерці",
		},

		new PlatformStringSet
		{
			Code = "bg",
			Cancel = "Отказ",
			Create = "Създаване",
			FolderNamePlaceholder = "Име на папката",
			KeepEditing = "Продължаване на редакцията",
			NameLabel = "Име:",
			NewFolder = "Нова папка",
			NoItems = "Няма елементи",
			Open = "Отваряне",
			OpenFileTitle = "Отваряне на файл",
			Replace = "Замяна",
			ReplaceFileFormat = "Да се замени ли „{0}“?",
			Save = "Запазване",
			SaveFileTitle = "Запазване на файл",
			SelectFolderTitle = "Избор на папка",
			Ok = "ОК",
			Yes = "Да",
			No = "Не",

			InformationTitle = "Информация",
			ErrorTitle = "Грешка",
			ErrorOccurredLabel = "Възникна грешка:",
			DetailsLabel = "Подробности:",
			ConfirmTitle = "Сигурни ли сте?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Изтр",
		},

		// Serbian written in Cyrillic script — the plain "sr" layout. Its Latin
		// counterpart is a separate set, in the Central Europe file.
		new PlatformStringSet
		{
			Code = "sr",
			Cancel = "Откажи",
			Create = "Направи",
			FolderNamePlaceholder = "Назив фасцикле",
			KeepEditing = "Настави уређивање",
			NameLabel = "Назив:",
			NewFolder = "Нова фасцикла",
			NoItems = "Нема ставки",
			Open = "Отвори",
			OpenFileTitle = "Отвори датотеку",
			Replace = "Замени",
			ReplaceFileFormat = "Заменити „{0}”?",
			Save = "Сачувај",
			SaveFileTitle = "Сачувај датотеку",
			SelectFolderTitle = "Изабери фасциклу",
			Ok = "У реду",
			Yes = "Да",
			No = "Не",

			InformationTitle = "Информације",
			ErrorTitle = "Грешка",
			ErrorOccurredLabel = "Дошло је до грешке:",
			DetailsLabel = "Детаљи:",
			ConfirmTitle = "Да ли сте сигурни?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Бриши",
		},

		new PlatformStringSet
		{
			Code = "mk",
			Cancel = "Откажи",
			Create = "Создај",
			FolderNamePlaceholder = "Име на папката",
			KeepEditing = "Продолжи со уредување",
			NameLabel = "Име:",
			NewFolder = "Нова папка",
			NoItems = "Нема ставки",
			Open = "Отвори",
			OpenFileTitle = "Отвори датотека",
			Replace = "Замени",
			ReplaceFileFormat = "Да се замени „{0}“?",
			Save = "Зачувај",
			SaveFileTitle = "Зачувај датотека",
			SelectFolderTitle = "Избери папка",
			Ok = "Во ред",
			Yes = "Да",
			No = "Не",

			InformationTitle = "Информации",
			ErrorTitle = "Грешка",
			ErrorOccurredLabel = "Се појави грешка:",
			DetailsLabel = "Детали:",
			ConfirmTitle = "Дали сте сигурни?",
			KeyAbc = "АБВ",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Бриши",
		},
	];
}
