#nullable enable

using System.Collections.Generic;

namespace CodeBrix.Platform.UI.Localization;

public static partial class PlatformStrings
{
	static IReadOnlyList<PlatformStringSet> NorthernEurope =>
	[
		new PlatformStringSet
		{
			Code = "da",
			Cancel = "Annuller",
			Create = "Opret",
			FolderNamePlaceholder = "Mappenavn",
			KeepEditing = "Fortsæt redigering",
			NameLabel = "Navn:",
			NewFolder = "Ny mappe",
			NoItems = "Ingen elementer",
			Open = "Åbn",
			OpenFileTitle = "Åbn fil",
			Replace = "Erstat",
			ReplaceFileFormat = "Vil du erstatte “{0}”?",
			Save = "Gem",
			SaveFileTitle = "Gem fil",
			SelectFolderTitle = "Vælg mappe",
			Ok = "OK",
			Yes = "Ja",
			No = "Nej",

			InformationTitle = "Information",
			ErrorTitle = "Fejl",
			ErrorOccurredLabel = "Der opstod en fejl:",
			DetailsLabel = "Detaljer:",
			ConfirmTitle = "Er du sikker?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Skift",
			KeyShiftUpper = "SKIFT",
			KeyBackspace = "Slet",
		},

		new PlatformStringSet
		{
			Code = "no",
			Cancel = "Avbryt",
			Create = "Opprett",
			FolderNamePlaceholder = "Mappenavn",
			KeepEditing = "Fortsett redigering",
			NameLabel = "Navn:",
			NewFolder = "Ny mappe",
			NoItems = "Ingen elementer",
			Open = "Åpne",
			OpenFileTitle = "Åpne fil",
			Replace = "Erstatt",
			ReplaceFileFormat = "Vil du erstatte «{0}»?",
			Save = "Lagre",
			SaveFileTitle = "Lagre fil",
			SelectFolderTitle = "Velg mappe",
			Ok = "OK",
			Yes = "Ja",
			No = "Nei",

			InformationTitle = "Informasjon",
			ErrorTitle = "Feil",
			ErrorOccurredLabel = "Det oppsto en feil:",
			DetailsLabel = "Detaljer:",
			ConfirmTitle = "Er du sikker?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Skift",
			KeyShiftUpper = "SKIFT",
			KeyBackspace = "Slett",
		},

		new PlatformStringSet
		{
			Code = "sv",
			Cancel = "Avbryt",
			Create = "Skapa",
			FolderNamePlaceholder = "Mappnamn",
			KeepEditing = "Fortsätt redigera",
			NameLabel = "Namn:",
			NewFolder = "Ny mapp",
			NoItems = "Inga objekt",
			Open = "Öppna",
			OpenFileTitle = "Öppna fil",
			Replace = "Ersätt",
			ReplaceFileFormat = "Vill du ersätta ”{0}”?",
			Save = "Spara",
			SaveFileTitle = "Spara fil",
			SelectFolderTitle = "Välj mapp",
			Ok = "OK",
			Yes = "Ja",
			No = "Nej",

			InformationTitle = "Information",
			ErrorTitle = "Fel",
			ErrorOccurredLabel = "Ett fel uppstod:",
			DetailsLabel = "Detaljer:",
			ConfirmTitle = "Är du säker?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Skift",
			KeyShiftUpper = "SKIFT",
			KeyBackspace = "Backsteg",
		},

		new PlatformStringSet
		{
			Code = "fi",
			Cancel = "Peruuta",
			Create = "Luo",
			FolderNamePlaceholder = "Kansion nimi",
			KeepEditing = "Jatka muokkaamista",
			NameLabel = "Nimi:",
			NewFolder = "Uusi kansio",
			NoItems = "Ei kohteita",
			Open = "Avaa",
			OpenFileTitle = "Avaa tiedosto",
			Replace = "Korvaa",
			ReplaceFileFormat = "Korvataanko ”{0}”?",
			Save = "Tallenna",
			SaveFileTitle = "Tallenna tiedosto",
			SelectFolderTitle = "Valitse kansio",
			Ok = "OK",
			Yes = "Kyllä",
			No = "Ei",

			InformationTitle = "Tiedot",
			ErrorTitle = "Virhe",
			ErrorOccurredLabel = "Tapahtui virhe:",
			DetailsLabel = "Lisätiedot:",
			ConfirmTitle = "Oletko varma?",
			KeyAbc = "ABC",
			KeyTab = "Sarkain",
			KeyEnter = "Enter",
			KeyShift = "Vaihto",
			KeyShiftUpper = "VAIHTO",
			KeyBackspace = "Askelp",
		},

		new PlatformStringSet
		{
			Code = "is",
			Cancel = "Hætta við",
			Create = "Búa til",
			FolderNamePlaceholder = "Heiti möppu",
			KeepEditing = "Halda áfram að breyta",
			NameLabel = "Heiti:",
			NewFolder = "Ný mappa",
			NoItems = "Engin atriði",
			Open = "Opna",
			OpenFileTitle = "Opna skrá",
			Replace = "Skipta út",
			ReplaceFileFormat = "Skipta út „{0}“?",
			Save = "Vista",
			SaveFileTitle = "Vista skrá",
			SelectFolderTitle = "Velja möppu",
			Ok = "Í lagi",
			Yes = "Já",
			No = "Nei",

			InformationTitle = "Upplýsingar",
			ErrorTitle = "Villa",
			ErrorOccurredLabel = "Villa kom upp:",
			DetailsLabel = "Nánar:",
			ConfirmTitle = "Ertu viss?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Shift",
			KeyShiftUpper = "SHIFT",
			KeyBackspace = "Bakk",
		},

		new PlatformStringSet
		{
			Code = "lt",
			Cancel = "Atšaukti",
			Create = "Sukurti",
			FolderNamePlaceholder = "Aplanko pavadinimas",
			KeepEditing = "Tęsti redagavimą",
			NameLabel = "Pavadinimas:",
			NewFolder = "Naujas aplankas",
			NoItems = "Elementų nėra",
			Open = "Atverti",
			OpenFileTitle = "Atverti failą",
			Replace = "Pakeisti",
			ReplaceFileFormat = "Pakeisti „{0}“?",
			Save = "Įrašyti",
			SaveFileTitle = "Įrašyti failą",
			SelectFolderTitle = "Pasirinkti aplanką",
			Ok = "Gerai",
			Yes = "Taip",
			No = "Ne",

			InformationTitle = "Informacija",
			ErrorTitle = "Klaida",
			ErrorOccurredLabel = "Įvyko klaida:",
			DetailsLabel = "Išsamiau:",
			ConfirmTitle = "Ar tikrai?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Lyg2",
			KeyShiftUpper = "LYG2",
			KeyBackspace = "Trinti",
		},

		new PlatformStringSet
		{
			Code = "lv",
			Cancel = "Atcelt",
			Create = "Izveidot",
			FolderNamePlaceholder = "Mapes nosaukums",
			KeepEditing = "Turpināt rediģēšanu",
			NameLabel = "Nosaukums:",
			NewFolder = "Jauna mape",
			NoItems = "Nav vienumu",
			Open = "Atvērt",
			OpenFileTitle = "Atvērt failu",
			Replace = "Aizstāt",
			ReplaceFileFormat = "Vai aizstāt “{0}”?",
			Save = "Saglabāt",
			SaveFileTitle = "Saglabāt failu",
			SelectFolderTitle = "Atlasīt mapi",
			Ok = "Labi",
			Yes = "Jā",
			No = "Nē",

			InformationTitle = "Informācija",
			ErrorTitle = "Kļūda",
			ErrorOccurredLabel = "Radās kļūda:",
			DetailsLabel = "Detalizēti:",
			ConfirmTitle = "Vai tiešām?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Pārsl",
			KeyShiftUpper = "PĀRSL",
			KeyBackspace = "Atpakaļ",
		},

		new PlatformStringSet
		{
			Code = "et",
			Cancel = "Loobu",
			Create = "Loo",
			FolderNamePlaceholder = "Kausta nimi",
			KeepEditing = "Jätka muutmist",
			NameLabel = "Nimi:",
			NewFolder = "Uus kaust",
			NoItems = "Üksusi pole",
			Open = "Ava",
			OpenFileTitle = "Ava fail",
			Replace = "Asenda",
			ReplaceFileFormat = "Kas asendada „{0}“?",
			Save = "Salvesta",
			SaveFileTitle = "Salvesta fail",
			SelectFolderTitle = "Vali kaust",
			Ok = "Sobib",
			Yes = "Jah",
			No = "Ei",

			InformationTitle = "Teave",
			ErrorTitle = "Tõrge",
			ErrorOccurredLabel = "Ilmnes tõrge:",
			DetailsLabel = "Üksikasjad:",
			ConfirmTitle = "Kas olete kindel?",
			KeyAbc = "ABC",
			KeyTab = "Tab",
			KeyEnter = "Enter",
			KeyShift = "Tõstuk",
			KeyShiftUpper = "TÕSTUK",
			KeyBackspace = "Kustuta",
		},
	];
}
