using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.CodeAnalysis.Testing;
using CodeBrix.Platform.Analyzers.Tests.Verifiers;
using System.Collections.Immutable;

namespace CodeBrix.Platform.Analyzers.Tests; //Was previously: Uno.Analyzers.Tests

using Verify = CSharpCodeFixVerifier<CodeBrixMissingAssemblyAnalyzer, EmptyCodeFixProvider>;

[TestClass]
public class CodeBrixMissingAssemblyAnalyzerTests
{
	// CodeBrix.Platform ships a single aggregate package (no UI/WinUI split). Requires the
	// package on a restorable feed (nuget.org once published, or src/PackageCache).
	private static readonly ImmutableArray<PackageIdentity> _codebrixPackage = [new PackageIdentity("CodeBrix.Platform.ApacheLicenseForever", "1.0.182.216")];
	private static readonly ImmutableArray<PackageIdentity> _codebrixPackageWithLottie = [new PackageIdentity("CodeBrix.Platform.ApacheLicenseForever", "1.0.182.216"), new PackageIdentity("CodeBrix.Platform.Lottie.ApacheLicenseForever", "1.0.182.216")];

	private static readonly ReferenceAssemblies _net100WithCodeBrix = ReferenceAssemblies.Net.Net100.AddPackages(_codebrixPackage);
	private static readonly ReferenceAssemblies _net100WithCodeBrixAndLottie = ReferenceAssemblies.Net.Net100.AddPackages(_codebrixPackageWithLottie);



	private const string CodeBrixHeadGlobalConfig = """
		is_global = true
		build_property.IsCodeBrixHead = true
		""";

	[TestMethod]
	public async Task UseProgressRingWithLottiePackage_NoDiagnostic()
	{
		var code = """
			using Microsoft.UI.Xaml.Controls;
			public class C
			{
				public ProgressRing M() => new ProgressRing();
			}
			""";

		var test = new Verify.Test()
		{
			TestCode = code,
			FixedCode = code,
			ReferenceAssemblies = _net100WithCodeBrixAndLottie,
		};

		test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", CodeBrixHeadGlobalConfig));

		await test.RunAsync();
	}

	[TestMethod]
	public async Task UseProgressRingWithoutLottiePackage_Diagnostic()
	{
		var code = """
			// <auto-generated />
			using Microsoft.UI.Xaml.Controls;
			public class C
			{
				public ProgressRing M() => [|new ProgressRing()|];
			}
			""";

		var test = new Verify.Test()
		{
			TestCode = code,
			FixedCode = code,
			ReferenceAssemblies = _net100WithCodeBrix,
		};

		test.TestState.AnalyzerConfigFiles.Add(("/.globalconfig", CodeBrixHeadGlobalConfig));

		await test.RunAsync();
	}

}
